### ISSUE TITLE
June 2022

### ISSUE THREAD

**Issue by akabekobeko** [vivliostyle/community#100]
|date | time | location|
|:--:|:--:|:--:|
|June 4, 2022 JST | 14:00-16:00 |Online|

- [Meeting Log](https://github.com/vivliostyle/community/blob/main/slack-logs/meeting-log/2022/2022-06-04.md)

## 法人からお知らせ

- [第4期事業報告書](https://github.com/vivliostyle/vivliostyle_doc/blob/gh-pages/ja/reports/vivliostyle-report-2021/%E4%B8%80%E8%88%AC%E7%A4%BE%E5%9B%A3%E6%B3%95%E4%BA%BA%E3%83%93%E3%83%96%E3%83%AA%E3%82%AA%E3%82%B9%E3%82%BF%E3%82%A4%E3%83%AB%202021%E5%B9%B4%E5%BA%A6%E4%BA%8B%E6%A5%AD%E5%A0%B1%E5%91%8A%E6%9B%B8.pdf)

## Core and Viewer（@MurakamiShinyu）

- 前月からの報告と今後の予定
    - アップデート
        - [v2.15.2 ](https://github.com/vivliostyle/vivliostyle.js/releases/tag/v2.15.2)
        - [v2.15.3 ](https://github.com/vivliostyle/vivliostyle.js/releases/tag/v2.15.3)
        - [v2.15.4](https://github.com/vivliostyle/vivliostyle.js/releases/tag/v2.15.4)
    - Vercelの費用軽減のためオープンソース申請→✅[ docs: Add "Powered by Vercel" banner #922 ](https://github.com/vivliostyle/vivliostyle.js/pull/922)

## CLI（@spring-raining）

- 前月からの報告と今後の予定
     - アップデート
        - [v4.12.2](https://github.com/vivliostyle/vivliostyle-cli/releases/tag/v4.12.2)
        - [v4.12.3](https://github.com/vivliostyle/vivliostyle-cli/releases/tag/v4.12.3)
        - [v4.12.4](https://github.com/vivliostyle/vivliostyle-cli/releases/tag/v4.12.4)
     - その他
       - https://github.com/vivliostyle/vivliostyle-cli/pull/291
       - GitHub Action for Vviliostyle https://github.com/vivliostyle/action

## VFM（@akabekobeko）

- 前月からの報告と今後の予定
     - アップデート
        - [v1.2.2](https://github.com/vivliostyle/vfm/releases/tag/v1.2.2)
     - その他

 ## create-book（@akabekobeko）

- 前月からの報告と今後の予定

## vivliostyle-sitegen（@akabekobeko）

- 前月からの報告と今後の予定
    - [ページ生成を再設計する #21 ](https://github.com/vivliostyle/vivliostyle-sitegen/issues/21)
    - [ サンプルを用意する #13 ](https://github.com/vivliostyle/vivliostyle-sitegen/issues/13)

## Themes（@yamasy1549）

- @逢賀サクさん提供の本文縦書2段組のtheme作成をすすめる（@yamasy1549）
- 印刷用のシンプルなthemeをすすめる（@UskeS）

## vivliostyle.org（@yamasy1549）

- [FAQに載せたいもの](https://github.com/vivliostyle/faq/issues)の項目を整理し、FAQの執筆をすすめる（@yamasy1549）
- 1分程度の簡単な動画作成
- vivliostyle-sitegen（@akabekobeko）との連携

## Vivliostyle Pub（@takanakahiko）

- 5月27日以降に開発再開
    - まずはどれがアクティブなIssueかを整理（@takanakahiko）
- アルファ版のアピール方法を考える（@MurakamiShinyu、@ogwata）
- Pubの開発に参加できるようコードをチェック（@MurakamiShinyu）
- モバイル版ブラウザの場合はメッセージを出すIssue作成 →✅[ モバイル対応していない旨を知ることができるようにする #183 ](https://github.com/vivliostyle/vivliostyle-pub/issues/183)
- 現在、Vercel管理が@MurakamiShinyuしかできない状態なのを解消するため、オープンソース申請をすすめるIssueを作成→✅[Vercel banner required to obtain the Vercel sponsorship for open source projects #182](https://github.com/vivliostyle/vivliostyle-pub/issues/182)
    - Vercel 使わず Firebase Hosting にするかは後日検討
- Safariでも動かせるようIssue作成（@MurakamiShinyu）→✅[[ Safari (WebKit)で動かない: "SyntaxError: Invalid regular expression: invalid group specifier name" #184 ](https://github.com/vivliostyle/vivliostyle-pub/issues/184)

## 次回日程

- 3日（日）
- 9日（土）
- 10日（日）

### Vercelへのオープンソース申請に伴うロゴ掲示について

- 前回合意にもとづき下記のように最少限度の掲示をして、Vercelに[申請中](https://vivliostyle.slack.com/archives/CNVBHM39V/p1654321263968469?thread_ts=1654316248.953259&cid=CNVBHM39V)
    - Vivliostyle Viewer
        - [開発版](https://vivliostyle.vercel.app/)に掲示
        - リポジトリの[README.md](https://github.com/vivliostyle/vivliostyle.js)に掲示
            - ✅[docs: Add "Powered by Vercel" banner #922](https://github.com/vivliostyle/vivliostyle.js/pull/922)
            - なお、[vivliostyle.org 上の初期画面](https://vivliostyle.org/viewer/)はVercelを使ってないので掲示しない
    - Vivliostyle Pub
        - ログオフ状態の初期画面で掲示（ログインすると消える）
        - リポジトリの[README.md](https://github.com/vivliostyle/vivliostyle-pub)に掲示
            - ✅[Vercel banner required to obtain the Vercel sponsorship for open source projects #182](https://github.com/vivliostyle/vivliostyle-pub/issues/182)

### Core and Viewer（@MurakamiShinyu）

- Vivliostyle Pubにコミットするため、現状可能な範囲でViewerのアップデートをしておいた。しばらくViewerの開発は打ち止めにして、Pubに集中したい。

### CLI（@spring-raining）

- Puppeteer を Playwright へ置き換える件
    - ✅[feat: Switch Puppeteer into Playwright #291](https://github.com/vivliostyle/vivliostyle-cli/pull/291)
    - この対応により、次のリリースでメジャーバージョンが5になる
    - それに伴い、node.jsの下限バージョンが14になる
    - ただし、CLI以外のプロダクトは現状のままとする（create-bookは例外）

### VFM（@akabekobeko）

- v1.2.2をリリース
    - ✅[fix: remove heading attributes notation on page title #148](https://github.com/vivliostyle/vfm/pull/148)
- [micromark](https://github.com/micromark/micromark)対応は、1ヵ月程度取りかかれない見込み

###  create-book（@akabekobeko）

- `.gitignore`ファイルが作られない件
    - ✅[Generated directory has no .gitignore file #11](https://github.com/vivliostyle/create-book/issues/11)
    - 早急に対応する→✅[ Fix not create gitignore #58 ](https://github.com/vivliostyle/create-book/pull/58)
- npx で vivliostyle コマンド使う方法をドキュメント化するかは保留
    - Issueたてる（@MurakamiShinyu）
- メジャーバージョンをv1とする
    -  これにともない、node.jsの下限バージョンを14とする（create-bookはCLIそのものを使うので例外）
    - ✅[Release v1.0 #53](https://github.com/vivliostyle/create-book/issues/53)

### Vivliostyle Pub（@takanakahiko）

- @MurakamiShinyu独自の判断でmergeする件
    - @takanakahikoと調整する→✅[Slack](https://vivliostyle.slack.com/archives/CR14JBXCJ/p1654329964904399)
- コントリビュータ増員のため、Qiita、Zennに投稿する（@ogwata）

### 次回日程

- 7月3日（いつもの土曜ではなく日曜開催なので、各自ご注意ください）

## Members

- @MurakamiShinyu
- @ogwata
- @spring-raining
- @yamasy1549
- @takanakahiko
- @UskeS
- @akabekobeko (Scribe)

**Comment by ogwata** [comment]
議事録案をまとめてみました。
他に話し合いたいこと等あれば、どんどんコメントください！

## 法人からお知らせ

- [第4期事業報告書](https://github.com/vivliostyle/vivliostyle_doc/blob/gh-pages/ja/reports/vivliostyle-report-2021/%E4%B8%80%E8%88%AC%E7%A4%BE%E5%9B%A3%E6%B3%95%E4%BA%BA%E3%83%93%E3%83%96%E3%83%AA%E3%82%AA%E3%82%B9%E3%82%BF%E3%82%A4%E3%83%AB%202021%E5%B9%B4%E5%BA%A6%E4%BA%8B%E6%A5%AD%E5%A0%B1%E5%91%8A%E6%9B%B8.pdf)

## Core and Viewer（@MurakamiShinyu）

- 前月からの報告と今後の予定
    - アップデート
        - [v2.15.2 ](https://github.com/vivliostyle/vivliostyle.js/releases/tag/v2.15.2)
        - [v2.15.3 ](https://github.com/vivliostyle/vivliostyle.js/releases/tag/v2.15.3)
        - [v2.15.4](https://github.com/vivliostyle/vivliostyle.js/releases/tag/v2.15.4)
    - Vercelの費用軽減のためオープンソース申請→✅[ docs: Add "Powered by Vercel" banner #922 ](https://github.com/vivliostyle/vivliostyle.js/pull/922)

## CLI（@spring-raining）

- 前月からの報告と今後の予定
     - アップデート
        - [v4.12.2](https://github.com/vivliostyle/vivliostyle-cli/releases/tag/v4.12.2)
        - [v4.12.3](https://github.com/vivliostyle/vivliostyle-cli/releases/tag/v4.12.3)
        - [v4.12.4](https://github.com/vivliostyle/vivliostyle-cli/releases/tag/v4.12.4)
     - その他

## VFM（@akabekobeko）

- 前月からの報告と今後の予定
     - アップデート
        - [v1.2.2](https://github.com/vivliostyle/vfm/releases/tag/v1.2.2)
     - その他

 ## create-book（@akabekobeko）

- 前月からの報告と今後の予定

## vivliostyle-sitegen（@akabekobeko）

- 前月からの報告と今後の予定
    - [ページ生成を再設計する #21 ](https://github.com/vivliostyle/vivliostyle-sitegen/issues/21)
    - [ サンプルを用意する #13 ](https://github.com/vivliostyle/vivliostyle-sitegen/issues/13)

## Themes（@yamasy1549）

- @逢賀サクさん提供の本文縦書2段組のtheme作成をすすめる（@yamasy1549）
- 印刷用のシンプルなthemeをすすめる（@UskeS）

## vivliostyle.org（@yamasy1549）

- [FAQに載せたいもの](https://github.com/vivliostyle/faq/issues)の項目を整理し、FAQの執筆をすすめる（@yamasy1549）
- 1分程度の簡単な動画作成
- vivliostyle-sitegen（@akabekobeko）との連携

## Vivliostyle Pub（@takanakahiko）

- 5月27日以降に開発再開
    - まずはどれがアクティブなIssueかを整理（@takanakahiko）
- アルファ版のアピール方法を考える（@MurakamiShinyu、@ogwata）
- Pubの開発に参加できるようコードをチェック（@MurakamiShinyu）
- モバイル版ブラウザの場合はメッセージを出すIssue作成 →✅[ モバイル対応していない旨を知ることができるようにする #183 ](https://github.com/vivliostyle/vivliostyle-pub/issues/183)
- 現在、Vercel管理が@MurakamiShinyuしかできない状態なのを解消するため、オープンソース申請をすすめるIssueを作成→✅[Vercel banner required to obtain the Vercel sponsorship for open source projects #182](https://github.com/vivliostyle/vivliostyle-pub/issues/182)
    - Vercel 使わず Firebase Hosting にするかは後日検討
- Safariでも動かせるようIssue作成（@MurakamiShinyu）→✅[[ Safari (WebKit)で動かない: "SyntaxError: Invalid regular expression: invalid group specifier name" #184 ](https://github.com/vivliostyle/vivliostyle-pub/issues/184)


## 次回日程

- 3日（日）
- 9日（土）
- 10日（日）

**Comment by ogwata** [comment]
合意事項をまとめてみました。過不足があればご指摘ください！


## 合意事項

### Vercelへのオープンソース申請に伴うロゴ掲示について

- 前回合意にもとづき下記のように最少限度の掲示をして、Vercelに[申請中](https://vivliostyle.slack.com/archives/CNVBHM39V/p1654321263968469?thread_ts=1654316248.953259&cid=CNVBHM39V)
    - Vivliostyle Viewer
        - [開発版](https://vivliostyle.vercel.app/)に掲示
        - リポジトリの[README.md](https://github.com/vivliostyle/vivliostyle.js)に掲示
            - ✅[docs: Add "Powered by Vercel" banner #922](https://github.com/vivliostyle/vivliostyle.js/pull/922)
            - なお、[vivliostyle.org 上の初期画面](https://vivliostyle.org/viewer/)はVercelを使ってないので掲示しない
    - Vivliostyle Pub
        - ログオフ状態の初期画面で掲示（ログインすると消える）
        - リポジトリの[README.md](https://github.com/vivliostyle/vivliostyle-pub)に掲示
            - ✅[Vercel banner required to obtain the Vercel sponsorship for open source projects #182](https://github.com/vivliostyle/vivliostyle-pub/issues/182)

### Core and Viewer（@MurakamiShinyu）

- Vivliostyle Pubにコミットするため、現状可能な範囲でViewerのアップデートをしておいた。しばらくViewerの開発は打ち止めにして、Pubに集中したい。

## CLI（@spring-raining）

- Puppeteer を Playwright へ置き換える件
    - ✅[feat: Switch Puppeteer into Playwright #291](https://github.com/vivliostyle/vivliostyle-cli/pull/291)
    - この対応により、次のリリースでメジャーバージョンが5になる
    - それに伴い、node.jsの下限バージョンが14になる
    - ただし、CLI以外のプロダクトは現状のままとする（create-bookは例外）

### VFM（@akabekobeko）

- v1.2.2をリリース
    - ✅[fix: remove heading attributes notation on page title #148](https://github.com/vivliostyle/vfm/pull/148)
- [micromark](https://github.com/micromark/micromark)対応は、1ヵ月程度取りかかれない見込み

###  create-book（@akabekobeko）

- `.gitignore`ファイルが作られない件
    - [Generated directory has no .gitignore file #11](https://github.com/vivliostyle/create-book/issues/11)
    - 早急に対応する→✅[ Fix not create gitignore #58 ](https://github.com/vivliostyle/create-book/pull/58)
- npx で vivliostyle コマンド使う方法をドキュメント化するかは保留
    - Issueたてる（@MurakamiShinyu）
- メジャーバージョンをv1とする
    -  これにともない、node.jsの下限バージョンを14とする（create-bookはCLIそのものを使うので例外）
    - ✅[Release v1.0 #53](https://github.com/vivliostyle/create-book/issues/53)

### Vivliostyle Pub（@takanakahiko）

- @MurakamiShinyu独自の判断でmergeする件
    - @takanakahikoと調整する→✅[Slack](https://vivliostyle.slack.com/archives/CR14JBXCJ/p1654329964904399)
- コントリビュータ増員のため、Qiita、Zennに投稿する（@ogwata）

### 次回日程

- 7月3日（いつもの土曜ではなく日曜なので、各自ご注意ください）

**Comment by akabekobeko** [comment]
ログをリンクしたので close します。
