### ISSUE TITLE
October 2022

### ISSUE THREAD

**Issue by akabekobeko** [vivliostyle/community#104]
|date | time | location|
|:--:|:--:|:--:|
|October 1, 2022 JST | 14:00-16:00 |Online|

- [Meeting Log](https://github.com/vivliostyle/community/blob/main/slack-logs/meeting-log/2022/2022-10-01.md)

### ゲストによるプレゼンテーション（10〜15分程度）

- [納品ドキュメントの作成にMarkdown+Vivliostyleを採用した話](https://qiita.com/tommyecguitar/items/2d1817cc8a09c15ad43e)（[とみー](https://twitter.com/PreddieNercury)）

### Core and Viewer（@MurakamiShinyu）

- [2.18.0 (2022-09-17)](https://github.com/vivliostyle/vivliostyle.js/blob/master/CHANGELOG.md#2180-2022-09-17)
- [2.18.1 (2022-09-18)](https://github.com/vivliostyle/vivliostyle.js/blob/master/CHANGELOG.md#2181-2022-09-18)
- [2.18.2 (2022-09-30)](https://github.com/vivliostyle/vivliostyle.js/blob/master/CHANGELOG.md#2182-2022-09-30)
- [2.18.3 (2022-09-30)](https://github.com/vivliostyle/vivliostyle.js/blob/master/CHANGELOG.md#2183-2022-09-30)

### CLI（@spring-raining）

- [5.6.0 (2022-09-24)](https://github.com/vivliostyle/vivliostyle-cli/blob/main/CHANGELOG.md#560-2022-09-24)
- [5.6.1 (2022-09-30)](https://github.com/vivliostyle/vivliostyle-cli/blob/main/CHANGELOG.md#561-2022-09-30)
- [5.6.2 (2022-09-30)](https://github.com/vivliostyle/vivliostyle-cli/blob/main/CHANGELOG.md#562-2022-09-30)
- 前月合意事項
    - Core最新バージョン[2.17.2 (2022-08-14)](https://github.com/vivliostyle/vivliostyle.js/releases/tag/v2.17.2)に伴うCLIのアップデート作業について、技術書典13ユーザーに配慮して保留していたが、6日以降に@spring-rainingに連絡した上で、@MurakamiShinyuが実施する

### VFM（@akabekobeko）

- 仕様について検討（sectionningにともなう問題）
    - [ spec: Attributes on auto-generated parent elements (section, figure) #151](https://github.com/vivliostyle/vfm/issues/151)
    - [ spec: Prevent auto-generation of section elements by headings inside explicit parent element #152](https://github.com/vivliostyle/vfm/issues/152)
    - [ spec: Options to control auto-sectioning #155 ](https://github.com/vivliostyle/vfm/issues/155)
    - [VFMの改善案について](https://vivliostyle.slack.com/files/TAE8V835Y/F043W6FPC6P)（@nosuke23）

###  create-book（@akabekobeko）

- （あれば）前月からの報告と今後の予定

### vivliostyle-sitegen（@akabekobeko）

- （あれば）前月からの報告と今後の予定

### Themes、[vivliostyle.org](http://vivliostyle.org/)（@yamasy1549）

- 前月合意事項
    - 技術書典用テーマとして@spring-rainingが CSS Variables を利用した[Themeを作成](https://github.com/ogwata/tbf13-draft/tree/main/theme)してくれたので、今後はこれを参照してVariables を活用していく

### Vivliostyle Pub（@takanakahiko、@MurakamiShinyu）

- 前月合意事項
    - β版（→[ ベータ版公開までのTo Do（開発） #218 ](https://github.com/vivliostyle/vivliostyle-pub/issues/218)）について、@MurakamiShinyuが作業した場合の日程を検討してみたが、それをするとCoreやViewer の開発が止まりPubにも悪影響がでるので、Core と Viewer を優先することにする
    - 開発者を拡大するため@MurakamiShinyuがこれまでのコミッターにメールを出す。その前提として@takanakahikoにクレデンシャル情報をふくめたドキュメント更新をお願いする（→[README 等の各種ドキュメンテーションが古いのでアップデートする #205 ](https://github.com/vivliostyle/vivliostyle-pub/issues/205)）

### その他

- 技術書典13の参加報告（@spring-raining）
- 「Vivliostyle ユーザーと開発者の集い 2022秋」の開催について（@ogwata）
    - 既定の企画
        - [鈴木丈氏（フォントワークス）による発表](https://terkel.jp/)
         - [スポンサーによるライトニングトーク](https://paper.dropbox.com/doc/Twitter--BplKveUJD5Y1I51yruhP6bR2Ag-fZNNGPpRj8H3tgqbwWKV3)
    - 検討事項（15分程度）
        - 登壇者とそのテーマ
        - 開催日程

### 次回日程

- 12月3日？

### VFM（@akabekobeko）

- [#151: 親要素への属性の移動・コピーをすべて廃止する案](https://github.com/vivliostyle/vfm/issues/151#issuecomment-1237660873)を採用とする（#151の当初案は取り下げ）
    - `section`要素へのスタイル指定には、近日中にVivliostyle.js で実装予定の`:has()`疑似クラスを使う
- [spec: Switch to control auto-sectioning #155 ](https://github.com/vivliostyle/vfm/issues/155)
    - 当初の自動的に`section`要素で囲むのをオプションで制御する案は取り下げ
    - 見出し階層数の`#`で囲むと当該の見出しでは`section`要素がつかないことにする案（by [@nosuke23](https://app.slack.com/docs/TAE8V835Y/F043W6FPC6P)）を採用とする

### 「Vivliostyle ユーザーと開発者の集い 2022秋」の開催について（@ogwata）

- @ogwata が発表案の叩き台を作成し、これを元に発表者と相談する
- 開催日は11月20日とする

## Members

- @MurakamiShinyu
- @ogwata
- @spring-raining
- @yamasy1549
- @takanakahiko
- @UskeS
- @akabekobeko (Scribe)

**Comment by ogwata** [comment]
すこし早いですが、議題を整理してみました。
もしこの後リリースがあれば適宜追加します。
他に話し合うことがあればコメントをお願いします。

-------
|date | time | location|
|:--:|:--:|:--:|
|October 1, 2022 JST | 14:00-16:00 |Online|

- [Meeting Log]()

## Agenda

### ゲストによるプレゼンテーション（10〜15分程度）

- [納品ドキュメントの作成にMarkdown+Vivliostyleを採用した話](https://qiita.com/tommyecguitar/items/2d1817cc8a09c15ad43e)（[とみー](https://twitter.com/PreddieNercury)）

### Core and Viewer（@MurakamiShinyu）

- [2.18.0 (2022-09-17)](https://github.com/vivliostyle/vivliostyle.js/blob/master/CHANGELOG.md#2180-2022-09-17)
- [2.18.1 (2022-09-18)](https://github.com/vivliostyle/vivliostyle.js/blob/master/CHANGELOG.md#2181-2022-09-18)

### CLI（@spring-raining）

- （あれば）前月からの報告と今後の予定

### VFM（@akabekobeko）

- （あれば）前月からの報告と今後の予定

###  create-book（@akabekobeko）

- （あれば）前月からの報告と今後の予定

### vivliostyle-sitegen（@akabekobeko）

- （あれば）前月からの報告と今後の予定

### Themes、[vivliostyle.org](http://vivliostyle.org/)（@yamasy1549）

- （あれば）前月からの報告と今後の予定

### Vivliostyle Pub（@takanakahiko、@MurakamiShinyu）

- （あれば）前月からの報告と今後の予定

### その他

- 技術書典13の参加報告（@spring-raining）
- 「Vivliostyle ユーザーと開発者の集い 2022秋」の開催について（@ogwata）
    - 既定事項
        - [鈴木丈氏（フォントワークス）による発表](https://terkel.jp/)
        - [技術書典13の執筆環境にVivliostyleを採用しました](https://zenn.dev/typebase/articles/techbookfest13-vivliostyle)（[@y_temp4](https://twitter.com/y_temp4)）
        - [スポンサーによるライトニングトーク](https://paper.dropbox.com/doc/Twitter--BplKveUJD5Y1I51yruhP6bR2Ag-fZNNGPpRj8H3tgqbwWKV3)
    - 検討事項（15分程度）
        - 登壇者とテーマ
        - 開催日程

### 次回日程

- 12月3日？

### Members

- @MurakamiShinyu
- @ogwata
- @spring-raining
- @yamasy1549
- @takanakahiko
- @UskeS
- @akabekobeko (Scribe)
- 
- その他、視聴者のみなさま

**Comment by ogwata** [comment]
皆さん、ご参加ありがとうございました。
合意をまとめてみました。どうかご確認を。

------------------

## 合意事項

### VFM（@akabekobeko）

- [#151: 親要素への属性の移動・コピーをすべて廃止する案](https://github.com/vivliostyle/vfm/issues/151#issuecomment-1237660873)を採用とする（#151の当初案は取り下げ）
    - section要素へのスタイル指定には、近日中にVivliostyle.js で実装予定の`:has()`疑似クラスを使う
- [spec: Switch to control auto-sectioning #155 ](https://github.com/vivliostyle/vfm/issues/155)
    - 当初の自動的にsection要素で囲むのをオプションで制御する案は取り下げ
    - 見出しの階層数の`#`で囲むと当該の見出しではsection要素がつかないことにする案（by [@nosuke23](https://app.slack.com/docs/TAE8V835Y/F043W6FPC6P)）を採用とする

### 「Vivliostyle ユーザーと開発者の集い 2022秋」の開催について（@ogwata）

- @ogwata が発表案の叩き台を作成し、これを元に発表者と相談する
- 開催日は11月20日とする
