### ISSUE TITLE
Vivliostyle 2020 Release Plan

### ISSUE THREAD

**Issue by uetchy** [vivliostyle/community#60]
# Overview

Vivliostyle 2020 will brings massive structural changes to core packages.

- [x] Adopt monorepo scheme for core packages (#621)
- [x] Rename npm modules along with a scoped namespace ([@vivliostyle](https://www.npmjs.com/org/vivliostyle))
- [x] Introduce semantic versioning (initial version is v2.0.0)
- [x] New document site

# Changes

## Logo

![Twitter Post - Vivliostyle](https://user-images.githubusercontent.com/431808/73133281-bcb5db80-4069-11ea-8192-2852c94000e6.png)

## Git repository

git remote URL won't be redirected. You need to manually set new git URL to following:

```
https://github.com/vivliostyle/vivliostyle.git
```

## API Changes (Core)

<img width="1012" alt="Twitter Post - What's New" src="https://user-images.githubusercontent.com/431808/72223601-fd1a5180-35b3-11ea-85ed-761168726091.png">

### Move directories

- /packages/print/demo/ → /packages/core/examples/printHTML/
- /packages/core/build/ → /scripts/
- /packages/viewer/scripts/ → /scripts/
- /packages/core/samples/ → /packages/viewer/pages/samples/
- /packages/core/typings/ → /packages/core/types/

#### /ts/*.ts → /*.ts
- /packages/core/src/ts/* → /packages/core/src/
- /packages/viewer/src/ts/* → /packages/viewer/src/

#### Documents has been relocated in vivliostyle.org
- /packages/core/src/ts/README.md → vivliostyle.org/docs/typescript-migration.md
- /packages/core/src/ts/_assets → vivliostyle.org/assets/typescript-migration/
- /packages/core/doc/* → vivliostyle.org/docs/
- /packages/viewer/dist/ → vivliostyle.org/docs/user-guide

### Files and Classes

- adaptviewer → adaptive-viewer (Viewer → AdaptiveViewer)
  - PageViewMode → AdaptivePageViewModede (avoid conflict with Vivliostyle Viewer's PageViewMode)
- viewer → core-viewer (Viewer → CoreViewer)
  - ViewerSettings → CoreViewerSettings
  - ViewerOptions → CoreViewerOptions  (avoid conflict with Vivliostyle Viewer's ViewerOptions)
- breakposition → break-position
- csscasc → css-cascade
- logical → css-logical-util
- cssparse → css-parser
- cssprop → css-prop
- cssstyler → css-styler
- csstok → css-tokenizer
- cssvalid → css-validator
- geom → geometry-util
- layouthelper → layout-helper
- layoutprocessor → layout-processor
- layoutretryers → layout-retryers
- layoututil → layout-util
- mathutil → math-util
- pagefloats → page-floats
- pm → page-master
- pseudoelement → pseudo-element
- repetitiveelement → repetitive-element
- taskutil → task-util
- viewerapp → viewer-app
- xmldoc → xml-doc

#### Browser (UMD)

```html
<script type="text/javascript" src="https://unpkg.com/@vivliostyle/core/lib/vivliostyle.js"></script>
<script type="text/javascript">
Vivliostyle.printHTML();
</script>
```

#### Browser (ES Modules)

```html
<script type="module">
import * as Vivliostyle from "https://unpkg.com/@vivliostyle/core/lib/esm/vivliostyle.js";
Vivliostyle.printHTML();
</script>
```

#### Node.js (CommonJS)

```js
const * as Vivliostyle = require("@vivliostyle/core");
Vivliostyle.printHTML();
```

## Bug fixes (Core)

- Fix circular dependency issue between `layout.ts` and `selectors.ts`.

## API Changes (Viewer)

- Omit development `<script>` injection thanks to Lerna's symlink feature.

#### Stable release

- **viewer:** https://vivliostyle.org/viewer/
- **archive:** https://vivliostyle.org/downloads/vivliostyle-latest.zip

#### Canary release (equivalent to `master`)

- **viewer:** https://vivliostyle.now.sh/

#### Tagged releases (Pre-release + Legacy releases)

https://vivliostyle.github.io/

- **viewer:** https://vivliostyle.github.io/viewer/vX.X.X/
- **archive:** https://github.com/vivliostyle/vivliostyle/releases/download/vX.X.X/vivliostyle-X.X.X.zip

## New documentation site

- [x] WIP

## Design system

<img width="1058" alt="Screen Shot 2020-01-26 at 18 32 08" src="https://user-images.githubusercontent.com/431808/73133308-3221ac00-406a-11ea-80c4-2a8256e19f0d.png">

# Schedule

### Rename repository (2019/12/14)

- [x] Rename GitHub repo (`vivliostyle/vivliostyle-savepdf`) to `vivliostyle/vivliostyle-cli`
- [x] Rewrite `package.json` and respective files to match its new name.

### Merge repositories (2019/12/14)

- [x] Merge `vivliostyle.js` commit history with `vivliostyle/vivliostyle#/packages/core`
- [x] Merge `vivliostyle-ui` commit history with `vivliostyle/vivliostyle#/packages/viewer`
- [x] Merge `vivliostyle-print` commit history with `vivliostyle/vivliostyle#/packages/print`

### Test and fix npm related issue (2019/12/14)

- [x] `npm i <scoped package>`
- [x] `lerna test`

### Transfer issues (2019/12/14)

- [x] Issues from `vivliostyle/vivliostyle.js` to `vivliostyle`
- [x] Issues from `vivliostyle/vivliostyle-ui` to `vivliostyle`

### Mark old repositories deprecated (2019/12/14)

- [x] Add notice and redirection to `vivliostyle/vivliostyle.js`
- [x] Add notice and redirection to `vivliostyle/vivliostyle-ui`
- [x] Add notice and redirection to `vivliostyle/vivliostyle-print`

### Archive deprecated repositories (Early 2020)

- [x] `vivliostyle/vivliostyle.js`
- [x] `vivliostyle/vivliostyle-ui`

### Re-organize documents

- [x] Move all documents to vivliostyle.org
- [x] Publish versioned documents

### Release scoped versions in npm (Early 2020)

- [x] `vivliostyle/vivliostyle#/packages/core` as `@vivliostyle/core#v2.0.0`
- [x] `vivliostyle/vivliostyle#/packages/viewer` as `@vivliostyle/viewer#v2.0.0`
- [x] `vivliostyle/vivliostyle-cli` as `@vivliostyle/cli#v2.0.0`

### `npm deprecate` (Early 2020)

- [ ] `vivliostyle`
- [ ] `vivliostyle-savepdf`
- [x] `vivliostyle-print`

## Remaining Tasks

- [x] Update documentation and websites to rewrite package name, module name, repository URL with its new name.

**Comment by MurakamiShinyu** [comment]
## Proposal to rename back vivliostyle/vivliostyle to vivliostyle/vivliostyle.js

- change the monorepo (core+viewer) repository name "vivliostyle" to "vivliostyle.js"
- the name "Vivliostyle.js" means Vivliostyle Core plus Viewer UI running on web browser's JavaScript engine
- the archive (download package) name will be `vivliostyle-js-<version>.zip` (e.g. `vivliostyle-js-latest.zip`, `vivliostyle-js-canary.zip`, `vivliostyle-js-v2.0.0.zip`)

**Reasons**:
- The name "Vivliostyle" should be the generic name for the Vivliostyle family products, including the Vivliostyle CLI and Vivliostyle Pub, and not only for Core + Viewer.  Using the name "Vivliostyle.js" for Core+Viewer can avoid confusion
- Links to Vivliostyle (core) issues/pulls in the past release notes and other documents were broken due to the repository URL change.  Renaming back to vivliostyle.js will solve this problem.

**Comment by akabekobeko** [comment]
昨年の計画 issue なので close します。
