### ISSUE TITLE
Vivliostyle Pub

### ISSUE THREAD

**Issue by uetchy** [vivliostyle/community#62]
![Slide](https://user-images.githubusercontent.com/431808/72223657-98132b80-35b4-11ea-8788-0e9d560588aa.png)

[**✍️Memo (ja)**](https://paper.dropbox.com/doc/Vivliostyle-Pub--AsTnzIXUtZJEXjI9sn_UjTCrAQ-o1SCfBLTcIdrKjWwF7SU9)
[**🧠Discussion**](https://vivliostyle.slack.com/archives/CR14JBXCJ)

**Comment by akabekobeko** [comment]
既に Pub プロジェクトは公開されて α 版リリースも近づいているため close します。

- [vivliostyle/vivliostyle-pub: Write, Collaborate, Publish.](https://github.com/vivliostyle/vivliostyle-pub)
-
