### ISSUE TITLE
February 2020

### ISSUE THREAD

**Issue by uetchy** [vivliostyle/community#63]
|date|time|location|
|---|---|---|
|February 2, 2020 JST|14:00-18:00|Denshoku, Inc.|

- [Meeting Log](https://github.com/vivliostyle/community/blob/master/slack-logs/meeting-log/2020-02-02.md)

# Agenda

### CFP (Call For Papers)

- 執筆者は現在 3 名、原稿の締め切り 2020/2/8 (土) まで受け付けしているのでぜひ参加を！ [tbf08_application](https://docs.google.com/spreadsheets/d/1S14R2YRbyJJGZN82DdNfO5ibEldCfP21hbJLb3Gzyrk/edit)
  - There are currently three authors, and the deadline for manuscripts will be accepted until JST 8/2/2020 (Sat), so please join us!
- 本と一緒に頒布するシールは新 Vivliostyle ロゴにします
  - The seal distributed with the book will be the new Vivliostyle logo

### Design review

- Figma の編集権は二人までなので、小形さんはコメントとして文章を書き、それを編集権を持つユーザーが反映する
  - Since Figma has up to two editors, Ogata writes a comment as a comment, which is reflected by users with editorial rights.
- ボタンなどのホバー効果を分かりやすくする、例えば変化を大きくするなど
  - Make hover effects such as buttons easy to understand. e.g. To increase the change.
- Web サイトのタイトルになる "The Vivliostyle Project ..." をもっと簡素にする
  - Making Web site title "The Vivliostyle Project ..." even simpler.
- 「Vivliostyle のなりたち」の原稿を書く
  - Writing a manuscript of "Now we are Vivliostyle"
- 原稿の表記、例えば和欧文の分かち書きなどを統一するための仕組みがほしい。これは [vivliostyle/vivliostyle.org](https://github.com/vivliostyle/vivliostyle.org). に issue 登録する
  - Want a mechanism to unify the manuscript notation, for example, Japanese and European writing. It registers an issue with [vivliostyle/vivliostyle.org](https://github.com/vivliostyle/vivliostyle.org).
- 「ドキュメント」は @yamasy1549 さんが月イチぐらいで更新可能
  - "Documents" can be updated by @ yamasy1549 in about a month.
- Web ブラウザーの言語設定を見てサイトの日英を切り替える
  - Switch between Japanese and English on the site by checking the language setting of the web browser

### Document site

- Web サイトと CLI を同時にリリースしたい
  - Want to release my website and CLI together
- CLI は [#34](https://github.com/vivliostyle/vivliostyle-cli/issues/34) を修正したらリリース予定、1 〜 2 週間ぐらい見込み
  - CLI will be released after fixing [#34](https://github.com/vivliostyle/vivliostyle-cli/issues/34). Expected for 1-2 weeks.
- 2020/2/9 に Web サイトと新ロゴ、Vivliostyle 2.0 はその後に改めてリリース予定
  - Web site and new logo on JST 2/7/2020 (Fri), Vivliostyle 2.0 will be released later

### PMF (Product Market Fit)

- まず「ユーザーに使ってもらえる」ことが重要なので初回リリースでは執筆機能の実装を優先する
  - First of all, it is important to have "users use", so in the first (initial) release, we will prioritize the implementation of the writing function.

### MVP (Minimum Viable Product)

- PDF だけでなく Web ブラウザー向けの表示も Vivliostyle としては必須
  - Display not only for PDF but also for web browser is required for Vivliostyle

### Technology stack

- [Vivliostyle Pub - Dropbox Paper](https://paper.dropbox.com/doc/Vivliostyle-Pub-o1SCfBLTcIdrKjWwF7SU9)
- [技術スタック - vivliostyle-pub](https://scrapbox.io/vivliostyle-pub/%E6%8A%80%E8%A1%93%E3%82%B9%E3%82%BF%E3%83%83%E3%82%AF)
- 会議から 3 週間後 (2 月末) に技術スタックの選定結果を出す
  - Three weeks after the meeting (end of February), a technology stack selection result will be issued
- 技術選定は vivliostyle-pub (private) の issue で議論する
  - Technology selection will be discussed in a vivliostyle-pub (private) issue
- サーバーレス系は特に大きな問題がなければ Firebase を採用する
  - Serverless adopt Firebase unless there is a major problem

### Ruby notation & Fenced blocks

- Fenced blocks と ruby 記法について議論されたが結論は出ず、個別の issue [#5](https://github.com/vivliostyle/vfm/issues/5) と [#10](https://github.com/vivliostyle/vfm/issues/10) で議論を継続
  - Fenced blocks and ruby notation were discussed, but no conclusion was reached. Continue discussions on individual issues [#5](https://github.com/vivliostyle/vfm/issues/5) and [#10](https://github.com/vivliostyle/vfm/issues/10).

# Full minutes

**Present:**
- @MurakamiShinyu
- @ogwata
- @spring-raining
- @akabekobeko
- @uetchy
- @yamasy1549
- @youchan

**Regrets:**

**Scribe:** @akabekobeko

**Comment by spring-raining** [comment]
I'd like to talk about the next articles of Techbookfest.

**Comment by akabekobeko** [comment]
本イベントを開催して議事録に Issue リンクを掲載したので close します。
