### ISSUE TITLE
Modification rule of Slack Logs

### ISSUE THREAD

**Issue by akabekobeko** [vivliostyle/community#73]
Consider the correction rule of Slack Log.

Currently, the log is directly converted to Markdown. However, there may be requests to correct problems and add supplements. Consider how to operate this.

現在の Slack Logs は JSON 形式のログをそのまま Markdown 変換している。しかし内容の問題修正や補足を追加したい要望もあるだろう。これをどのように運用するか検討する。

**Comment by akabekobeko** [comment]
私の考える案。

1. Issue として要望してもらう
2.  今後 Slack Logs は #70 により本リポジトリーで直にファイル管理されるので `git clone` してもらって直 commit - push か PR を作ってもらう

1 は最も手軽。GitHub 上で Issue 作成するだけなので Git 操作も不要である。基本はこちらを推したい。これは #71 でテンプレートを用意すると更に親切。

2 は直だと権限、PR の場合は GitHub 自体の知識が必要。これをサポートするなら手順書を用意して負担軽減したい。

**Comment by ogwata** [comment]
基本的な考え方として、なるべく多くの人に議事録の編集に参加してもらいたいとおもっていｍ
可能であれば、1と2の両方ともサポートしていただけるとありがたいです。

**Comment by akabekobeko** [comment]
@ogwata  はい。両方サポートしましょう。

1 については明文化と Issue Template (ユーザー補助) で対応します。2 は高度なオプションですね。Markdown ファイルを直に編集するのはよほど多くの修正や補足となるので基本的に 1 推しでゆきたいと思います。

**Comment by akabekobeko** [comment]
ルールに 1 と 2、どちらも可能なことを記載する予定です。

**Comment by akabekobeko** [comment]
年単位で放置されているので整理のために close します。必要ならば re-open するか新規 issue を起票してください。
