### ISSUE TITLE
September 2020

### ISSUE THREAD

**Issue by akabekobeko** [vivliostyle/community#76]
|date | time | location|
|:--:|:--:|:--:|
|September 13, 2020 JST | 14:00 (Advisors) / 15:00 (Developers) - 17:00 |Online|

- [Meeting Log](https://github.com/vivliostyle/community/blob/master/slack-logs/meeting-log/2020/2020-09-13.md)

###  8月〜9月活動報告 (小形)

- [Create Book のチュートリアルページを公開](https://vivliostyle.org/ja/documents/#%E3%83%81%E3%83%A5%E3%83%BC%E3%83%88%E3%83%AA%E3%82%A2%E3%83%AB%E3%82%AC%E3%82%A4%E3%83%89)
- [Create Book の特集企画を公開](https://vivliostyle.org/ja/make-books-with-create-book/)
- [Vivliostyleユーザ会発行「Vivliostyleで本を作ろう！」第4号に編集協力](https://techbookfest.org/product/6649486623375360?productVariantID=6028446700404736)
- 自費出版のサポート事業（制作代行等）を開始、第1号は村上さんのお母様
-  各方面にVivliostyle Pubの開発パートナーをお願いする活動中

### 新たな戦略目標の提案 (小形)

- 短期目標
    - [CLIリポジトリで3.0.0-pre.3がmasterになっているのをv2.1にもどす](https://github.com/vivliostyle/vivliostyle-cli/issues/78)
    - [CLI 3.0を安定して使えるよう熟成する](https://github.com/vivliostyle/vivliostyle-cli/issues)
    - createｰbookをはじめ、VFM、themesの開発、熟成
    - より多くのユーザが使えるようcreateｰbookにGUIラッパーを追加できないか検討
- 中期目標
    - Vivliostyle Pubのローカル版としてCreate Bookを訴求する
    - それを材料にパートナーを獲得
    - Vivliostyle Pub の開発再開
- 長期目標
    - Vivliostyle Pub のローンチ

### 新たな戦略目標の提案 (小形)

- 短期目標
    - [CLIリポジトリで3.0.0-pre.3がmasterになっているのをv2.1にもどす](https://github.com/vivliostyle/vivliostyle-cli/issues/78)
    - [CLI 3.0を安定して使えるよう熟成する](https://github.com/vivliostyle/vivliostyle-cli/issues)
    - createｰbookをはじめ、VFM、themesの開発、熟成
    - より多くのユーザが使えるようcreateｰbookにGUIラッパーを追加できないか検討
- 中期目標
    - Vivliostyle Pubのローカル版としてCreate Bookを訴求する
    - それを材料にパートナーを獲得
    - Vivliostyle Pub の開発再開
- 長期目標
    - Vivliostyle Pub のローンチ

### Vivliostyle ユーザーと開発者の集い 2020秋の開催の検討

- テーマ、日程、スピーカー等

### Vivliostyle Pub開発再開の条件について

- 開発者が希望する報酬その他

### ヨーロッパ “One Button Publishing” プロジェクト（Fidus Writer + Vivliostyle）の紹介

- https://vivliostyle.slack.com/archives/CJRP7PK6K/p1599049196002200
- https://lh4.googleusercontent.com/JTrCibecATKGygto-rfR1DyowEAHEsMIx8BiHQcNGI90lRKRHKfkIAPvsUuQ89E8CVJLIa0kYMVsapt6EqtmkC4zJ2ZI26EEt1m_cE5gX4orkfh_r3imO7SnWLKOlmQQXXQQ1sms
- https://github.com/Independent-SAGE/Technical-Publishing-Working-Group

### Vivliostyle CLI 3.0について

- https://github.com/vivliostyle/vivliostyle-cli/issues

### theme について

- @yamasy1549 themeをカスタマイズできるよう
- @MurakamiShinyu パラメータ設定に参考になる既存書籍作成サービスの調査
  - https://vivliostyle.slack.com/archives/CNN5GPF9V/p1599215469001600

### 技術書典 9

- [Vivliostyleで本を作ろう Vol.4：Vivliostyleユーザー会](https://techbookfest.org/product/6649486623375360?productVariantID=6028446700404736) について

## Members

- @MurakamiShinyu
- @ogwata
- @spring-raining
- @youchan
- @yamasy1549
- @takanakahiko
- @llminatoll (Advisors)
- @lwohtsu (Advisors)
- @kondoyuko (Advisors)
- @akabekobeko (Scribe)

**Comment by ogwata** [comment]
- 8月〜9月活動報告（小形）
- Vivliostyle Pub開発再開の条件について
    - 開発者が希望する報酬その他
- ヨーロッパ “One Button Publishing” プロジェクト（Fidus Writer + Vivliostyle）の紹介
    - https://vivliostyle.slack.com/archives/CJRP7PK6K/p1599049196002200
    - https://lh4.googleusercontent.com/JTrCibecATKGygto-rfR1DyowEAHEsMIx8BiHQcNGI90lRKRHKfkIAPvsUuQ89E8CVJLIa0kYMVsapt6EqtmkC4zJ2ZI26EEt1m_cE5gX4orkfh_r3imO7SnWLKOlmQQXXQQ1sms
- Vivliostyle CLI 3.0について
    - https://github.com/vivliostyle/vivliostyle-cli/issues
- theme について
    - やましー：themeをカスタマイズできるよう
    - 村上：パラメータ設定に参考になる既存書籍作成サービスの調査

**Comment by akabekobeko** [comment]
@ogwata Agenda に反映しました

**Comment by MurakamiShinyu** [comment]
> - ヨーロッパ “One Button Publishing” プロジェクト（Fidus Writer + Vivliostyle）の紹介

以下、そのメモです：

4月に公開の記事,
ドイツ国立科学技術図書館が Vivliostyle により、COVID-19対策の公衆衛生教科書を出版
https://vivliostyle.org/ja/blog/2020/04/10/tib-book-against-covid19/

最近(9月2日)、このTIB(ドイツ国立科学技術図書館)側の開発者であるSimon Worthington (サイモン・ワージントン)氏から q-and-a チャンネルに投稿。
https://vivliostyle.slack.com/archives/CJRP7PK6K/p1599049196002200
このスレッドで、このプロジェクトのその後が次のように報告されています。

Fidus WriterとVivliostyleを使用して、ドイツ語でさらに5冊のHealth Learning本を作成しました:

- Der Kinder-und Jugendgesundheitsdienst (子どもと若者の健康サービス)
  https://akademie-oeffentliches-gesundheitswesen.github.io/KJGD/
- Begutachtung im Öffentlichen Gesundheitsdienst (保健医療サービスにおける評価)
  https://akademie-oeffentliches-gesundheitswesen.github.io/Begutachtung/
- Der Öffentliche Gesundheitsdienst (公衆衛生局)
  https://akademie-oeffentliches-gesundheitswesen.github.io/OeGD/
- Der Sozialpsychiatrische Dienst (社会精神医学サービス)
  https://akademie-oeffentliches-gesundheitswesen.github.io/SpDi/
- Sozialmedizinische Assistenten/innen (社会医療補助員)
  https://akademie-oeffentliches-gesundheitswesen.github.io/SMA/

（「PDF」というリンクからVivliostyle出力のPDF版、「Web-Buch」(Web Book)というリンクからVivliostyle Viewer表示））

しかし今、このしくみを強化して可能ならもっと自動化を追加したい。→「One Button Publishing」計画の概要
https://vivliostyle.slack.com/archives/CJRP7PK6K/p1599049325003000?thread_ts=1599049196.002200&cid=CJRP7PK6K

また、英国のIndie_SAGEがレポートを公開するのを支援する自発的なワーキンググループを結成し、7月初旬にサンプルテストを実施した：

https://independent-sage.github.io/Should-Schools-Reopen/#/

インディペンデントSAGEは、英国政府の元首席科学者が率いるCOVID-19について助言する科学グループ。

PDFまたはDOCXからマルチフォーマットへの迅速な出版ワークフローをセットアップする必要があるレポートは約20ある。

（以下、「One Button Publishing」計画の概要の一部を紹介）

- 目的：マルチフォーマットの書籍「出版物パッケージ」をFidus WriterからWebサイトとして公開する。スクリーンPDF、PoD PDF、ウェブサイト用Markdown、eBook、Vivliostyleウェブブックを含む。そして、「出版物パッケージ」をGitリポジトリとして利用できるようにする。
- 目標：この計画の目的は、迅速な書籍制作システムを必要としているクライアントがいるので、このシステムを最速で提供する方法を見つけることです（2020年9月中旬）。
- 利用者：公衆衛生関係者

![](https://lh4.googleusercontent.com/JTrCibecATKGygto-rfR1DyowEAHEsMIx8BiHQcNGI90lRKRHKfkIAPvsUuQ89E8CVJLIa0kYMVsapt6EqtmkC4zJ2ZI26EEt1m_cE5gX4orkfh_r3imO7SnWLKOlmQQXXQQ1sms)

- フルMVPを完成させるために修正が必要な部分:
    1.  Fidus Writer の出版物モデルとUI・機能
    2.  エクスポートと出版物のパッケージング
    3.  マルチフォーマットの出版物出力

- 「Fast-track MVP」では対象となる課題を減らし、1ボタン・パブリッシングで自動マルチフォーマット出版出力を作成することに注力: (⭐️: Vivliostyle関係)
    -   Repo publishing template
    -   Publication repo
    -   Website publishing container
    -   Website - Hugo / Docsify
    -   eBook - EPUB 3.0 (validated to EPUB 3.2 with EPUBCheck 4.2.4)
    -   Web book - Vivliostyle⭐️
    -   Screen PDF - bookmarks, metadata⭐️
    -   PoD PDF - covers and spine, recto/verso ordering (manual, or semi-manual)⭐️
    -   Metadata for all formats, repositories, academia and citation, international sales channels - free, trade & including all pricing and discounts, social media, SEO/Web, PIDs and tracker IDs

- CSS組版、Vivliostyle と Fidus Writer への質問

    現在、FWからの出力ファイルをVivliostyleで動作するようにするには、HTML、CSS、その他のアセットを手動で編集しなければならないという問題がある。

    FW ファイルが書籍用の Vivliostyle で完全に動作するように移行する必要がある。

    その問題のリスト：

- **Paged CSS or Adaptive Layout?** Which approach to CSS Typesetting do you think we should take?

- **Vivliostyle - 'named pages' and 'add page blank':** For us to use 'Paged CSS' then we need Vivliostyle to support 'named pages' and 'add page blank', our understanding is currently these are not supported. If these are not supported we'll need to use 'Adaptive Layout' for creating things like: blank pages with no folios or for applying custom styles to other pages and effectively sections - like making an index more compact.

- **Main CSS Typesetting issue when using FW files in Vivliostyle:** 

    1.  Having a section of page styles so we can turn off folios and page numbers displaying on specific pages or sections, i.e., on blank pages, or front matter etc. If we can't use 'named pages' and 'add page blank' then we'd need to use section HTML tag. Currently we have to hack things by having 'Front Matter' in the index.html file along with the ToC. So likely we'd like FW to add a Sections Tag to Documents and say by using Document Templates be able to add a custom or preset number of section data names - cover, title page, front matter, text, back matter, blank, etc.

    2.  For Vivliostyle: If we use 'Adaptive Layout' we get a bug when applying page blank before a page, for example on Chapter starts - as sometimes the following Chapter text section would mistakenly fall a page in front of where it should be - so starting before the chapter. We can share an example code.

    3.  Back cover: We need to exclude folios from the 'back cover' page of a book. It seems common that people get this problem with Paged CSS and use a DIV and CLASS to insert an image, but this means manual code editing.

    4.  A back cover image: Since FW renames uploaded images it is not possible to have a constant name of an image like 'backcover.jpg' and reference this in CSS. Would it be possible in the book setting to upload a backcover.jpg alongside the existing cover.jpg as is used for the EPUB.

    5.  Exact positioning of page elements on FW for Vivliostyle layouts: It is not possible for us to do complex and accurate artwork and textbox positioning etc., using FW. Are there any ideas about how this could be done? Or is this out of scope for FW.

- その他の質問
    1.  FW: Could FW generate simple MD or Scholarly MD?
    2.  FW: Can FW GitHub export - export to specific directory locations? E.g., pdf file in /pdf, etc.
    3.  We need to generate a PDF from the Vivliostyle - can we set up a CI process to do this on GitHub - note we have access to a GCP resource with a large amount of credits.
    4.  Metadata needs a place to be authored, stored and inserted into outputs, or made available for copy / paste into distribution channels.
    5.  PDFs - need metadata adding and bookmarks.

- Current manual workflow
    ...

**Comment by ogwata** [comment]
「8月〜9月活動報告（小形）」に次行に以下を追加

- 以下の目標を設定したい（項目が上であるほど直近）
    - 短期目標
        - [CLIリポジトリで3.0.0-pre.3がmasterになっているのをv2.1にもどす](https://github.com/vivliostyle/vivliostyle-cli/issues/78)
        - CLI 3.0を安定して使えるよう熟成する
        - createｰbookをはじめ、VFM、themeの開発、熟成
        - より多くのユーザが使えるようcreateｰbookにGUIラッパーを追加できないか検討
    - 中期目標
        - Vivliostyle Pubのローカル版としてCreate Bookを訴求する
        - それを材料にスポンサーを獲得
        - Vivliostyle Pub の開発再開
    - 長期目標
        - Vivliostyle Pub のローンチ
- Vivliostyle ユーザーと開発者の集い 2020秋の開催の検討
    - テーマ、日程、スピーカー等

**Comment by ogwata** [comment]
>     * パラメータ設定に参考になる既存書籍作成サービスの調査

この部分に、下記のリンクを追加してください。

https://vivliostyle.slack.com/archives/CNN5GPF9V/p1599215469001600

**Comment by akabekobeko** [comment]
反映しました。Advisors の方で議題があればお願いします。現時点だと何もありません。

**Comment by ogwata** [comment]
> 反映しました。

すいません、現状では「8月〜9月活動報告（小形）」の下位に目標の件とイベントの件が含まれることになっています。

「以下の目標を設定したい（項目が上であるほど直近） 」から「テーマ、日程、スピーカー等」までを、そっくり1レベル上位に変更してください。

その上で、「以下の目標を設定したい（項目が上であるほど直近） 」を「新たな戦略目標の提案（小形）」に置き換えてください。

> Advisors の方で議題があればお願いします。現時点だと何もありません。

重複しますが、Advisersにも「新たな戦略目標の提案（小形）」のスレッドをそのまま入れてください。

**Comment by akabekobeko** [comment]
@ogwata 反映しました。ついでに階層を全体的にひとつ浅くしています。

> 重複しますが、Advisersにも「新たな戦略目標の提案（小形）」のスレッドをそのまま入れてください。

とあるのでそのままコピペしてあります。

**Comment by spring-raining** [comment]
時間があれば技術書典での状況について説明しようと思います。

**Comment by akabekobeko** [comment]
@spring-raining Developers の末尾へ議題として追加しました。

**Comment by ogwata** [comment]
直前にすみません。活動報告の詳細です。

# 活動報告（2020年8月9日-9月13日）

- [Create Book のチュートリアルページを公開](https://vivliostyle.org/ja/documents/#%E3%83%81%E3%83%A5%E3%83%BC%E3%83%88%E3%83%AA%E3%82%A2%E3%83%AB%E3%82%AC%E3%82%A4%E3%83%89)
- [Create Book の特集企画を公開](https://vivliostyle.org/ja/make-books-with-create-book/)
- [Vivliostyleユーザ会発行「Vivliostyleで本を作ろう！」第4号に編集協力](https://techbookfest.org/product/6649486623375360?productVariantID=6028446700404736)
- 自費出版のサポート事業（制作代行等）を開始、第1号は村上さんのお母様
-  各方面にVivliostyle Pubの開発パートナーをお願いする活動中

**Comment by ogwata** [comment]
@akabekobeko 

すいません、活動報告をAdvisersに移動させてもらえませんか。
Developerの参加者は、ほとんどAdvisers の方にも参加している感じなので。

**Comment by akabekobeko** [comment]
@ogwata 活動報告を反映 & Advisors 冒頭へ移動しました。

**Comment by akabekobeko** [comment]
ミーティング開催 & 議事録を追加したので close
