### ISSUE TITLE
2020 秋のユーザー会イベントを開催する

### ISSUE THREAD

**Issue by akabekobeko** [vivliostyle/community#77]
本 Issue では以下を検討して開催する。

- 登壇者
- 日時

**Comment by akabekobeko** [comment]
登壇者で決定している方。

- @lwohtsu
- @yamasy1549

**Comment by akabekobeko** [comment]
現在の候補日は

- 10/24 (土)
- 11/7  (土)

**Comment by ogwata** [comment]
以下のように決定

[CSS組版 Vivliostyle ユーザーと開発者の集い 2020秋 ](https://vivliostyle.connpass.com/event/189940/)
