### ISSUE TITLE
November 2020

### ISSUE THREAD

**Issue by akabekobeko** [vivliostyle/community#79]
|date | time | location|
|:--:|:--:|:--:|
|November 8, 2020 JST | 14:00- |Online|

- [Meeting Log](https://github.com/vivliostyle/community/blob/master/slack-logs/meeting-log/2020/2020-11-08.md)

## Agenda

- イベント振り返り [CSS組版 Vivliostyle ユーザーと開発者の集い 2020秋 - connpass](https://vivliostyle.connpass.com/event/189940/)
  - Paged.js と Vivliostyle  https://github.com/akabekobeko/examples-vivliostyle-pagedjs の比較評価のレビューについて
  - [「Paged.js を試す」 @akabekobeko のレビュー](https://gist.github.com/MurakamiShinyu/e907f9dabf689ad10a24362a25121cd9)
- Vivliostyle Pub 開発の要件定義
  - [「Vivliostyle Pub v1 要件仕様」ドラフト](https://github.com/vivliostyle/community/wiki/Vivliostyle-Pub-v1-Req)
- [外部との協議](https://vivliostyle.slack.com/archives/G012JJWU23U/p1604482568115800)
    - 工場見学OK（[東京都足立区](https://www.shimaya.net/information/company.html)）とのことだが、希望者いる？
- [技術書典10への対応について](https://blog.techbookfest.org/2020/11/01/tbf10-announcement/)
- 次回日程の確認

## Members

- @MurakamiShinyu
- @ogwata
- @spring-raining
- @yamasy1549
- @takanakahiko
- @akabekobeko (Scribe)

Guest:

- Shin Kuboaki
- shimura
- ym tk

**Comment by akabekobeko** [comment]
とりあえず必要そうな議題

- イベント振り返り [CSS組版 Vivliostyle ユーザーと開発者の集い 2020秋 - connpass](https://vivliostyle.connpass.com/event/189940/)
- Vivliostyle Pub 開発の要件定義

**Comment by ogwata** [comment]
- [しまや出版との提携について](https://vivliostyle.slack.com/archives/G012JJWU23U/p1604482568115800)
    - 工場見学OK（[東京都足立区](https://www.shimaya.net/information/company.html)）とのことだが、希望者いる？
- [技術書典10への対応について](https://blog.techbookfest.org/2020/11/01/tbf10-announcement/)

**Comment by MurakamiShinyu** [comment]
イベント振り返りに入るかもしれませんが、 @akabekobeko さんの Paged.js と Vivliostyle  https://github.com/akabekobeko/examples-vivliostyle-pagedjs の比較評価のレビューについて https://gist.github.com/MurakamiShinyu/e907f9dabf689ad10a24362a25121cd9 少しお話ししたいです。

**Comment by akabekobeko** [comment]
ここまでのコメントを Agenda へ反映させました

**Comment by MurakamiShinyu** [comment]
> - Vivliostyle Pub 開発の要件定義

「Vivliostyle Pub v1 要件仕様」ドラフト
https://github.com/vivliostyle/community/wiki/Vivliostyle-Pub-v1-Req
途中まで書いて中断してましたが、これから書きます。
そのうえで、開発会議で議論したい点をまとめようと思います。

**Comment by akabekobeko** [comment]
議題にドラフトをリンクしました。

**Comment by ogwata** [comment]
下記を最後の項目として追加してください。

- 次回日程の確認

**Comment by akabekobeko** [comment]
@ogwata 追加しました

**Comment by akabekobeko** [comment]
ミーティング開催 & 議事録を追加したので close します。
