### ISSUE TITLE
February 2021

### ISSUE THREAD

**Issue by akabekobeko** [vivliostyle/community#84]
|date | time | location|
|:--:|:--:|:--:|
|February 6, 2021 JST | 14:00-16:40 |Online|

- [Meeting Log](https://github.com/vivliostyle/community/blob/master/slack-logs/meeting-log/2021/2021-02-06.md)

## Agenda

- [vfm-viewer](https://github.com/Monchi/vfm-viewer)のデモ（@Monchi） 

### VFM の仕様検討

VFMの仕様と現状の動作をチェックして各spec issueのコメントに課題と仕様見直し案をまとめた:

- [spec: Auto generate HTML section elements #8](https://github.com/vivliostyle/vfm/issues/8)
  - [コメント: 現状の vfm と Pandoc --section-divs の動作の比較評価](https://github.com/vivliostyle/vfm/issues/8#issuecomment-760207841)
- [spec: Attributes on headings and other elements #9](https://github.com/vivliostyle/vfm/issues/9)
  - [コメント: 現状の vfm での実装状況と課題](https://github.com/vivliostyle/vfm/issues/9#issuecomment-760304439)
- [spec: figure for image container #15](https://github.com/vivliostyle/vfm/issues/15)
  - [コメント: 現状の課題まとめ](https://github.com/vivliostyle/vfm/issues/15#issuecomment-760331260)
- [spec: Fenced blocks #5](https://github.com/vivliostyle/vfm/issues/5)
  - [コメント: 現状の vfm の Fenced blocks 実装とその課題、Pandoc との比較 / HTML 要素名を明示的に指定可能にする拡張案](https://github.com/vivliostyle/vfm/issues/5#issuecomment-768119623)
- [spec: WAI-ARIA role syntax #28](https://github.com/vivliostyle/vfm/issues/28)
  - [コメント: WAI-ARIA role syntax の見直し案](https://github.com/vivliostyle/vfm/issues/28#issuecomment-768171789)

@akabekobeko からの議題:

- VFM v1.0.0 進捗報告
- [svgタグ内の改行がbrタグに変換される · Issue #38 · vivliostyle/vfm](https://github.com/vivliostyle/vfm/issues/38)
  - [CommonMark Spec 4.6 HTML blocks](https://spec.commonmark.org/0.29/#html-blocks) のリストにないタグが分割処理される挙動をどう扱うか？
  - remark としては CommonMark に基づきブロック扱いしない
  - VFM として対応するなら既定を CommonMark 互換としてオプショナルにブロック処理を実装するか？

### vivliostyle.js v2.5 で予定する更新内容について報告

- [feat(viewer): Configuration flags update](https://github.com/vivliostyle/vivliostyle.js/pull/693)
- [break-before:left/right at beginning of a document does not work properly](https://github.com/vivliostyle/vivliostyle.js/issues/666)
- [First-page pseudo-class :first should work on each document in a multi-document publication? (→support :nth())](https://github.com/vivliostyle/vivliostyle.js/issues/667)

### vivliostyle-cli v3 RC

近日中にリリース予定の v3 RC について @spring-raining

> Hi users! I’m planning to release the RC version of vivliostyle-cli v3 in a few days. If that version seems to be works well, it’ll become the final release before the major update to v3.

## 合意事項
- vfm-viewerのデモ
    - yukuさんがCLIへのPRを検討する
-  デフォルトブランチ名について `master` を `main` に変更するか
   - 新しいものはデフォルトの `main` に、旧来のものは変更しない
   - Vivliostyle Pub は変更する
- VFM の仕様検討
    -  Fenced Block 実装は現時点だと Pandoc 仕様に対して中途半端なので、**いったん**ドロップする
    - 変換結果をこうしてほしいというテストファイルを村上がPRで提供し、それにもとづき議論する
        -  [markedjs/marked](https://github.com/markedjs/marked/tree/master/test/specs/redos)
        - [RFC: Ruby annotation #65](https://github.com/vivliostyle/vfm/pull/65)
    - [svgタグ内の改行がbrタグに変換される · Issue 38](https://github.com/vivliostyle/vfm/issues/38)
        - 規定ではなくオプションに変更する方向で継続議論
    - Vivliostyle CLI V3、2月7日リリース
    - 次回日程
        - 3月7日（日曜日）14時〜

## Members

- @MurakamiShinyu
- @ogwata
- @spring-raining
- @yamasy1549
- @takanakahiko
- @AyumuTakai
- @Monchi
- liarnose
- Cojiro
- @akabekobeko (Scribe)

**Comment by MurakamiShinyu** [comment]
議題案：

VFMの仕様と現状の動作をチェックして各spec issueのコメントに課題と仕様見直し案をまとめた:

- [spec: Auto generate HTML section elements #8](https://github.com/vivliostyle/vfm/issues/8)
  - [コメント: 現状の vfm と Pandoc --section-divs の動作の比較評価](https://github.com/vivliostyle/vfm/issues/8#issuecomment-760207841)
- [spec: Attributes on headings and other elements #9](https://github.com/vivliostyle/vfm/issues/9)
  - [コメント: 現状の vfm での実装状況と課題](https://github.com/vivliostyle/vfm/issues/9#issuecomment-760304439)
- [spec: figure for image container #15](https://github.com/vivliostyle/vfm/issues/15)
  - [コメント: 現状の課題まとめ](https://github.com/vivliostyle/vfm/issues/15#issuecomment-760331260)
- [spec: Fenced blocks #5](https://github.com/vivliostyle/vfm/issues/5)
  - [コメント: 現状の vfm の Fenced blocks 実装とその課題、Pandoc との比較 / HTML 要素名を明示的に指定可能にする拡張案](https://github.com/vivliostyle/vfm/issues/5#issuecomment-768119623)
- [spec: WAI-ARIA role syntax #28](https://github.com/vivliostyle/vfm/issues/28)
  - [コメント: WAI-ARIA role syntax の見直し案](https://github.com/vivliostyle/vfm/issues/28#issuecomment-768171789)

**Comment by akabekobeko** [comment]
@MurakamiShinyu 議題に追加しました

**Comment by ogwata** [comment]
以下の議題の追加をお願いします。

- [vfm-viewer](https://github.com/Monchi/vfm-viewer)のデモ（@Monchi）

**Comment by akabekobeko** [comment]
@ogwata 冒頭に追加しました

**Comment by MurakamiShinyu** [comment]
議題案:
- vivliostyle.js v2.5 で予定する更新内容について報告
  - [feat(viewer): Configuration flags update](https://github.com/vivliostyle/vivliostyle.js/pull/693)
  - [break-before:left/right at beginning of a document does not work properly](https://github.com/vivliostyle/vivliostyle.js/issues/666)
  - [First-page pseudo-class :first should work on each document in a multi-document publication? (→support :nth())](https://github.com/vivliostyle/vivliostyle.js/issues/667)

**Comment by akabekobeko** [comment]
@MurakamiShinyu 追加しました

**Comment by ogwata** [comment]
## 合意事項
-

**Comment by akabekobeko** [comment]
@ogwata 個別の項目にわけて追記しようと考えていましたが、小形さんの書式そのままのほうが一覧性があり読みやすいので末尾に転載しました。

**Comment by akabekobeko** [comment]
Meeting Log をリンクしたので本件は close する。
