### ISSUE TITLE
2021 春のユーザー会イベントを開催する

### ISSUE THREAD

**Issue by akabekobeko** [vivliostyle/community#86]
本 Issue では以下を検討して開催する。

- 登壇者
- 日時

本 issue または Slack の meetup チャンネルで挙げられて合意を得られたものは随時、ここに記載してゆく。

## イベント告知

- [CSS組版 Vivliostyle ユーザーと開発者の集い 2021春 - connpass](https://vivliostyle.connpass.com/event/208401/)

## 開催日時

- 2021/4/10 (土) 13:00

## 登壇

- @yamasy1549
  - themeのハンズオン（仮）
- @AyumuTakai
  - CLIのアップデート案（仮）
- @ogwata
  - Create Bookを使った旅行エッセイ本の制作
- @MurakamiShinyu
  -  Vivliostyleはなにを目指すか——CSS Paged Media の実装
- 逢賀サク
  -  同人作家から見たVivliostyleへの期待

**Comment by akabekobeko** [comment]
開催日時は 2021/4/10 (土) 13:00 を予定。

**Comment by ogwata** [comment]
## 現在のスピーカー（3/19現在）

- @yamasy1549 : themeのハンズオン（仮）
- @AyumuTakai CLIのアップデート案（仮）
- @ogwata : Vivliostyle CLI v3を使った旅行エッセイ本の制作
- @MurakamiShinyu : Vivliostyleはなにを目指すか——CSS Paged Media の実装

引き続き、企画募集中
できれば3/23くらいから告知を介したいです！

**Comment by ogwata** [comment]
私の論題ですが、以下のように変更します。

Vivliostyle CLI v3を使った旅行エッセイ本の制作
↓
Create Bookを使った旅行エッセイ本の制作

Vivliostyle CLI v3を使っているのは間違いないのですが、主眼は「本作り」なので、そうなるとCreate Bookと書いた方がより相応しいと思いました。

**Comment by akabekobeko** [comment]
Slack にて逢賀サクさんから登壇希望があったので追加。

**Comment by akabekobeko** [comment]
タイムテーブルがほぼ確定して connpass により告知された。そのまま開催されるはずなので本件は close する。
