### ISSUE TITLE
May 2021

### ISSUE THREAD

**Issue by akabekobeko** [vivliostyle/community#87]
|date | time | location|
|:--:|:--:|:--:|
|May 8, 2021 JST | 14:00-16:00 |Online|

- [Meeting Log](https://github.com/vivliostyle/community/blob/master/slack-logs/meeting-log/2021/2021-05-08.md)

### 進捗報告と今後の開発方針

- Core
- CLI
- VFM
- Themes
  - CSS Paged Media等、最新機能を活用できるThemeができないか
  - 同人小説のための Theme
  - 欧文文庫テーマ
  - その他
- CreateBook
- Pub
  - 日程について

### 公式サイト・ドキュメントの見直し

- 最近の開発動向をふまえ、どんなコンテンツが充実できるか
  - Awesome
  - tipsなどなど

### 「Vivliostyle で本を作ろう Vol. 5」の制作

- [技術書典11 開催およびサークル募集開始のお知らせ - 技術書典ブログ](https://blog.techbookfest.org/2021/04/23/tbf11-announcement/)
- @spring-raining

#### Core
- Issueの中から優先度の高いものを選んで提示する（→@shinyu）
#### CLI
- themeの追加については、基本的にインストールされた theme をコピーするだけにして、元の npm scriptの更新等は追従しなくてよいこととする
- Issueを優先度順に整理する（→@spring-raining）

#### VFM

- メタデータに関する新規Issueをたててそこで議論（→@akabekobeko）
    - →[メタデータと Frontmatter 再考 #98](https://github.com/vivliostyle/vfm/issues/98)

#### Themes 

- [逢賀サクさん](https://twitter.com/ogs_52843)さんに、同人小説用themeでどんな機能が欲しいか問い合わせる（→@yamasy1549）
- 「Vivliostyleで本を作ろう！」用のthemeを汎用的なthemeとして公開できないか、検討する（@spring-raining）

#### CreateBook

- 以下のIssueに意見をだす（→everybody）
    - [create-book を akabeko がリリースしてみる #23](https://github.com/vivliostyle/create-book/issues/23)
    - [npm publish doesn't change npm create templates #27](https://github.com/uetchy/create-create-app/issues/27)

#### Pub

- 1.0ベータは、7月には動くものを内部レビューでき、9月末にはベータ公開できることを目指す（→@takanakahiko）
- あわせて複数人で開発可能な体制を構築する（→@takanakahiko）
- 終わらなさそうな場合はなるべく早く報告する（→@takanakahiko）

## 公式サイト・ドキュメントの見直し

- 以下のIssueで議論を継続する（→everybody）
    - [注目のissueを一覧にする #78](https://github.com/vivliostyle/vivliostyle.org/issues/78)
    - [ユーザーガイドにVFMのドキュメントを追加 #79](https://github.com/vivliostyle/vivliostyle.org/issues/79)
    - [使ってみるページのCLIの説明を更新 #80](https://github.com/vivliostyle/vivliostyle.org/issues/80)
    - [サンプルの更新 #81](https://github.com/vivliostyle/vivliostyle.org/issues/81)
    - [ダウンロードページの更新 #82](https://github.com/vivliostyle/vivliostyle.org/issues/82)
    - [FAQページの更新 #83](https://github.com/vivliostyle/vivliostyle.org/issues/83)
- ドキュメントページの更新について、GitHub Issue のパラメーターを拾って自動生成する方法を検討する（@yamasy1549）

## Vivliostyleで本を作ろう vol.5の編集について

- 原稿の締切は 2021/6/13
- 公式サイトのブログで執筆者募集の告知をする（→@spring-raining）
- VFM リポジトリーでいう docs/vfm.md を平易な日本語で書くような記事で寄稿（→@akabekobeko）
- themes の作り方、あたりで検討予定（@yamasy1549）
- 2020年度のVivliostyle活動レポート（注：「旅行記の制作記事」から変更しました →@ogwata）
- なにか書けないか検討する（→@AyumuTakai）

## 次回日程

- 2021/6/12 (土) 

## Members

- @MurakamiShinyu
- @ogwata
- @spring-raining
- @yamasy1549
- @takanakahiko
- @AyumuTakai
- hideyuki kanno
- @akabekobeko (Scribe)

**Comment by akabekobeko** [comment]
@ogwata @MurakamiShinyu 
開催日が間近ですので議題をお願いします。

**Comment by ogwata** [comment]
遅れてすみません、対応しますので少しお待ちください。

**Comment by akabekobeko** [comment]
@ogwata 反映しました

**Comment by ogwata** [comment]
最後に以下を追加してください。

- 「Vivliostyle で本を作ろう Vol. 4」の制作 @spring-raining

**Comment by akabekobeko** [comment]
@ogwata 反映しました

**Comment by MurakamiShinyu** [comment]
Vol. 4 の反省？　こんど作るのは Vol. 5 ですね

**Comment by akabekobeko** [comment]
@ogwata @MurakamiShinyu Vol.5 に直しました

**Comment by ogwata** [comment]
ごめんなさい、今気づいたのですが「「Vivliostyle で本を作ろう Vol. 5」の制作 @spring-raining」はH2でした！

**Comment by akabekobeko** [comment]
@ogwata 
合意事項まとめをお願いします。それを議題末尾へ記載したことをもって本 issue を close 予定です。

**Comment by akabekobeko** [comment]
議題冒頭に議事録のリンクを貼ったので、合意事項の参考にしてください。

**Comment by ogwata** [comment]
合意事項をまとめてみました。
これで違和感ないか、皆さんご確認ください。（とくにassignされた人）

## 合意事項
### 進捗報告と今後の開発方針
#### Core
- Issueの中から優先度の高いものを選んで提示する（→@shinyu）

#### CLI
- themeの追加については、基本的にインストールされた theme をコピーするだけにして、元の npm scriptの更新等は追従しなくてよいこととする
- Issueを優先度順に整理する（→@spring-raining）
#### VFM
- メタデータに関する新規Issueをたてる（→@akabeko）
    - →[メタデータと Frontmatter 再考 #98](https://github.com/vivliostyle/vfm/issues/98)
#### Themes 
- [逢賀サクさん](https://twitter.com/ogs_52843)さんに、同人小説用themeでどんな機能が欲しいか問い合わせる（→@yamasy1549）
- 「Vivliostyleで本を作ろう！」用のthemeを汎用的なthemeとして公開できないか、検討する（@spring-raining）

#### CreateBook
- 以下のIssueに意見をだす（→everybody）
    - [create-book を akabeko がリリースしてみる #23](https://github.com/vivliostyle/create-book/issues/23)
    - [npm publish doesn't change npm create templates #27](https://github.com/uetchy/create-create-app/issues/27)
    - 
#### Pub
- 1.0ベータは、7月には動くものを内部レビューでき、9月末にはベータ公開できることを目指す（→@takanakahiko）
- あわせて複数人で開発可能な体制を構築する（→@takanakahiko）
- 終わらなさそうな場合はなるべく早く報告する（→@takanakahiko）
## 公式サイト・ドキュメントの見直し
- 以下のIssueで議論を継続する（→everybody）
    - [注目のissueを一覧にする #78](https://github.com/vivliostyle/vivliostyle.org/issues/78)
    - [ユーザーガイドにVFMのドキュメントを追加 #79](https://github.com/vivliostyle/vivliostyle.org/issues/79)
    - [使ってみるページのCLIの説明を更新 #80](https://github.com/vivliostyle/vivliostyle.org/issues/80)
    - [サンプルの更新 #81](https://github.com/vivliostyle/vivliostyle.org/issues/81)
    - [ダウンロードページの更新 #82](https://github.com/vivliostyle/vivliostyle.org/issues/82)
    - [FAQページの更新 #83](https://github.com/vivliostyle/vivliostyle.org/issues/83)
- ドキュメントページの更新について、GitHub Issue のパラメーターを拾って自動生成する方法を検討する（@yamasy1549）
## Vivliostyleで本を作ろう vol.5の編集について
- 原稿の締切は 2021/6/13
- 公式サイトのブログで執筆者募集の告知をする（→@spring-raining）
- VFM リポジトリーでいう docs/vfm.md を平易な日本語で書くような記事で寄稿（→@akabeko）
- themes の作り方、あたりで検討予定（@yamasy1549）
- 2020年度のVivliostyle活動レポート（注：その後変更しました →@ogwata）
- なにか書けないか検討する（→@Ayumu Takai）

## 次回日程
- 2021/6/12 (土)

**Comment by akabekobeko** [comment]
@ogwata 
@takanakahiko さん以外は OK なのと @takanakahiko さんのスケジュール想定はご本人によるものでしたので合意とみなして issue 冒頭へ転載しました。

この対応をもって本件は close します。
