### ISSUE TITLE
June 2021

### ISSUE THREAD

**Issue by akabekobeko** [vivliostyle/community#88]
|date | time | location|
|:--:|:--:|:--:|
|June 12, 2021 JST | 14:00-16:00 |Online|

- [Meeting Log](https://github.com/vivliostyle/community/blob/master/slack-logs/meeting-log/2021/2021-06-12.md)

#### Core（@shinyu）

- Issueの中から優先度の高いものを選んで提示する

#### CLI（@spring-raining）

- Issueを優先度順に整理する

#### VFM（@akabekobeko）

- メタデータに関する新規Issueをたててそこで議論

#### Themes （@yamasy1549）

- [逢賀サクさん](https://twitter.com/ogs_52843)さんに、同人小説用themeでどんな機能が欲しいか問い合わせる
- 「Vivliostyleで本を作ろう！」用のthemeを汎用的なthemeとして公開できないか、検討する（@spring-raining）

#### CreateBook（@akabekobeko）

- 以下のIssueに意見をだす（→everybody）
    - [create-book を akabeko がリリースしてみる #23](https://github.com/vivliostyle/create-book/issues/23)
    - [npm publish doesn't change npm create templates #27](https://github.com/uetchy/create-create-app/issues/27)

#### Pub（@takanakahiko）

- 1.0ベータは、7月には動くものを内部レビューでき、9月末にはベータ公開できることを目指す
- あわせて複数人で開発可能な体制を構築する
- 終わらなさそうな場合はなるべく早く報告する

### 2020年度活動報告書（@ogwata）

- 「年度中のできごとのまとめ」の形で執筆をすすめたが、村上の指摘で「年度末時点の成果のまとめ」に変更することに
- 現在[Create vivliostyle report 2020 #5](https://github.com/vivliostyle/vivliostyle_doc/pull/5)で執筆中
- 6/18までには公開したい

### 6/15 JEPAセミナーで村上と小形が講演予定（@ogwata）

- {あしたのVivliostyle：オープンソースCSS組版システムがつくる未来](https://kokucheese.com/event/index/611843/)
- 村上がVivliostyleの技術要件の解説を、小形が使用事例を話す予定
- 講演後、Zoom交流会を15～30分ほど開催。そこで提携先を模索したい

### 進捗報告と今後の開発方針

- Core
    -  実装、対応を希望する Issue について Reaction で 👍 を付ける →everybody
    -   公式サイトの[今後の開発予定](https://vivliostyle.org/ja/documents/#%E4%BB%8A%E5%BE%8C%E3%81%AE%E9%96%8B%E7%99%BA%E4%BA%88%E5%AE%9A)に、P1 - P2ラベルのIssue、別項として good first issueラベルのIssueに手動でリンクを張る →@yamasy1549 
    - 他のリポジトリもcoreを参考にしてラベル付けをする →@spring-raining @akabekobeko @yamasy1549 @takanakahiko 
- Themes
    - 逢賀サクさんと協力しつつ新しいThemeを作成する →@yamasy1549 
    - Themesの命名法について[Issueを作った](https://github.com/vivliostyle/themes/issues/48)ので、ここで議論をする →everybody
    - 「Vivliostyle で本を作ろう」を元にした新Themeは、機能を絞りシンプルなものとして再編する →@yamasy1549 
- Pub
    - 先月の合意事項（以下）のその後について回答する → @takanakahiko 
        - 1.0ベータは、7月には動くものを内部レビューでき、9月末にはベータ公開できることを目指す
        - あわせて複数人で開発可能な体制を構築する
        - 終わらなさそうな場合はなるべく早く報告する

### 公式サイト・ドキュメントの見直し
- 以下のIssueで議論を継続する @MurakamiShinyu @yamasy1549 
    - [注目のissueを一覧にする #78](https://github.com/vivliostyle/vivliostyle.org/issues/78)
    - [ユーザーガイドにVFMのドキュメントを追加 #79](https://github.com/vivliostyle/vivliostyle.org/issues/79)
    - [使ってみるページのCLIの説明を更新 #80](https://github.com/vivliostyle/vivliostyle.org/issues/80)
    - [サンプルの更新 #81](https://github.com/vivliostyle/vivliostyle.org/issues/81)
    - [ダウンロードページの更新 #82](https://github.com/vivliostyle/vivliostyle.org/issues/82)
    - [FAQページの更新 #83](https://github.com/vivliostyle/vivliostyle.org/issues/83)
- ドキュメントページの更新について、GitHub Issue のパラメーターを拾って自動生成する方法を検討する（@yamasy1549）

### Vivliostyleで本を作ろう vol.5の編集について
- 逢賀サクさん @AyumuTakai 執筆を検討、可能なら[エントリーする](https://docs.google.com/spreadsheets/d/1s4lbu7MQFKhSSZveHOVH6BhDe35PJaalNshsNZuGhwA/edit?usp=sharing)

## Members

- @MurakamiShinyu
- @ogwata
- @spring-raining
- @yamasy1549
- @AyumuTakai
- 逢賀サク
- @akabekobeko (Scribe)

**Comment by ogwata** [comment]
お待たせしてすみませんが、10日午後には議題をまとめて投稿します。

**Comment by ogwata** [comment]
議題を考えてみました。

## [前月](https://github.com/vivliostyle/community/issues/87)の振り返りと進捗の報告（プロダクトごとに前回合意事項のその後を報告、あわせて現時点の課題を共有／検討）
#### Core（@shinyu）
- Issueの中から優先度の高いものを選んで提示する
#### CLI（@spring-raining）
- Issueを優先度順に整理する
#### VFM（@akabekobeko）
- メタデータに関する新規Issueをたててそこで議論
#### Themes （@yamasy1549）
- [逢賀サクさん](https://twitter.com/ogs_52843)さんに、同人小説用themeでどんな機能が欲しいか問い合わせる
- 「Vivliostyleで本を作ろう！」用のthemeを汎用的なthemeとして公開できないか、検討する（@spring-raining）
#### CreateBook（@akabekobeko）
- 以下のIssueに意見をだす（→everybody）
    - [create-book を akabeko がリリースしてみる #23](https://github.com/vivliostyle/create-book/issues/23)
    - [npm publish doesn't change npm create templates #27](https://github.com/uetchy/create-create-app/issues/27)
#### Pub（@takanakahiko）
- 1.0ベータは、7月には動くものを内部レビューでき、9月末にはベータ公開できることを目指す
- あわせて複数人で開発可能な体制を構築する
- 終わらなさそうな場合はなるべく早く報告する
## その他の検討課題
### 公式サイト・ドキュメントの見直し（@akabekobeko）
### 「Vivliostyle で本を作ろう Vol. 5」の制作I（@spring-raining）
## その他報告
### 2020年度活動報告書（@ogwata）
- 「年度中のできごとのまとめ」の形で執筆をすすめたが、村上の指摘で「年度末時点の成果のまとめ」に変更することに
- 現在[Create vivliostyle report 2020 #5](https://github.com/vivliostyle/vivliostyle_doc/pull/5)で執筆中
- 6/18までには公開したい
### 6/15 JEPAセミナーで村上と小形が講演予定（@ogwata）
- {あしたのVivliostyle：オープンソースCSS組版システムがつくる未来](https://kokucheese.com/event/index/611843/)
- 村上がVivliostyleの技術要件の解説を、小形が使用事例を話す予定
- 講演後、Zoom交流会を15～30分ほど開催。そこで提携先を模索したい

**Comment by akabekobeko** [comment]
@ogwata 反映しました

**Comment by ogwata** [comment]
合意事項のまとめですが、15日のJEPAセミナーがすんだ16日までお待ちいただけませんか。
すみません！

**Comment by akabekobeko** [comment]
議事録リンクを追加

**Comment by ogwata** [comment]
遅くなってすみません！　合意事項をまとめてみました。
なにか漏れがあればご指摘を。


## 合意事項

### 進捗報告と今後の開発方針

- Core
    -  実装、対応を希望する Issue について Reaction で 👍 を付ける →everybody
    -   公式サイトの[今後の開発予定](https://vivliostyle.org/ja/documents/#%E4%BB%8A%E5%BE%8C%E3%81%AE%E9%96%8B%E7%99%BA%E4%BA%88%E5%AE%9A)に、P1 - P2ラベルのIssue、別項として good first issueラベルのIssueに手動でリンクを張る →@yamasy1549 
    - 他のリポジトリもcoreを参考にしてラベル付けをする →@spring-raining @akabekobeko @yamasy1549 @takanakahiko 
- Themes
    - 逢賀サクさんと協力しつつ新しいThemeを作成する →@yamasy1549 
    - Themesの命名法について[Issueを作った](https://github.com/vivliostyle/themes/issues/48)ので、ここで議論をする →everybody
    - 「Vivliostyle で本を作ろう」を元にした新Themeは、機能を絞りシンプルなものとして再編する →@yamasy1549 
- Pub
    - 先月の合意事項（以下）のその後について回答する → @takanakahiko 
        - 1.0ベータは、7月には動くものを内部レビューでき、9月末にはベータ公開できることを目指す
        - あわせて複数人で開発可能な体制を構築する
        - 終わらなさそうな場合はなるべく早く報告する

### 公式サイト・ドキュメントの見直し
- 以下のIssueで議論を継続する @MurakamiShinyu @yamasy1549 
    - [注目のissueを一覧にする #78](https://github.com/vivliostyle/vivliostyle.org/issues/78)
    - [ユーザーガイドにVFMのドキュメントを追加 #79](https://github.com/vivliostyle/vivliostyle.org/issues/79)
    - [使ってみるページのCLIの説明を更新 #80](https://github.com/vivliostyle/vivliostyle.org/issues/80)
    - [サンプルの更新 #81](https://github.com/vivliostyle/vivliostyle.org/issues/81)
    - [ダウンロードページの更新 #82](https://github.com/vivliostyle/vivliostyle.org/issues/82)
    - [FAQページの更新 #83](https://github.com/vivliostyle/vivliostyle.org/issues/83)
- ドキュメントページの更新について、GitHub Issue のパラメーターを拾って自動生成する方法を検討する（@yamasy1549）

### Vivliostyleで本を作ろう vol.5の編集について
- 逢賀サクさん @AyumuTakai 執筆を検討、可能なら[エントリーする](https://docs.google.com/spreadsheets/d/1s4lbu7MQFKhSSZveHOVH6BhDe35PJaalNshsNZuGhwA/edit?usp=sharing)

**Comment by akabekobeko** [comment]
合意事項を掲載したので本件は close します。
