### ISSUE TITLE
September 2021

### ISSUE THREAD

**Issue by akabekobeko** [vivliostyle/community#91]
|date | time | location|
|:--:|:--:|:--:|
|September 4, 2021 JST | 14:00-16:00 |Online|

- [Meeting Log]()

[前月](https://github.com/vivliostyle/community/issues/90)の振り返りと進捗報告（プロダクトごとに前回合意事項からの進捗を報告）

## Core and Viewer (@MurakamiShinyu)

- 前月合意事項
    - vivliostyle-view.js について
        - 告知のためブログを執筆→@MurakamiShinyu
- 前月からの進捗報告

## CLI (@spring-raining)

- 前月からの進捗報告

## Themes (@yamasy1549)

- 前月合意事項
    - 同人誌themeについて、逢賀サクさんの素材データを元に作成する
- [既存の公式テーマの名前を考え直す #56](https://github.com/vivliostyle/themes/issues/56)
    - →議論し忘れ、Issueで継続議論しましょう→everyone
- 「Vivliostyle で本を作ろう」を元にした新Themeは、機能を絞りシンプルなものとして再編する
    - → @spring-raining  の報告を待つ

## VFM (@akabekobeko)

- 前月合意事項
    - ["Vivliostyle Flavored Markdown: Working Draft"](https://vivliostyle.github.io/vfm/#/vfm#table-of-contents) のタイトルにある「Working Draft」はそのまま削除する
    - [公式リファレンスの Working Draft 表記を削除する · Issue #122 · vivliostyle/vfm](https://github.com/vivliostyle/vfm/issues/122)
- 前月からの進捗報告

## npm管理関連

- 前月合意事項
    - Node.jsの Requirement versionについて、下限をv12とする
    - Vivliostyleプロダクト全体で下限を一致させる必要があるので、各担当者はプロジェクトごとにIssueを作成して、下限を設定する
        - Core and Viewer→@MurakamiShinyu
        - CLI →@spring-raining
        - Themes (@yamasy1549) →[Node.jsの Requirement version を設定する #59](https://github.com/vivliostyle/themes/issues/59)
        - Vivliostyle Pub →@takanakahiko
    - native ESMの対応は来年以降、状況を見極めつつおこなう

## vivliostyle.org (@yamasy1549)

- 前月合意事項
    - VFM 1.0.2リリースにともない、[今後の開発予定](https://vivliostyle.org/ja/documents/#%E4%BB%8A%E5%BE%8C%E3%81%AE%E9%96%8B%E7%99%BA%E4%BA%88%E5%AE%9A)のVFMの項は、[v2.0.0](https://github.com/vivliostyle/vfm/milestone/1)に変更する →[VFM注目のissueをv2.0.0のmilestoneに変更する #95](https://github.com/vivliostyle/vivliostyle.org/issues/95)
    - [FAQページの更新 #83](https://github.com/vivliostyle/vivliostyle.org/issues/83)

## Vivliostyle Pub (@takanakahiko)

- [ オープンベータまでのTo Doを考える（開発） #89 ](https://github.com/vivliostyle/vivliostyle-pub/issues/89)
- [ オープンベータまでのTo Doを考える（開発以外） #82 ](https://github.com/vivliostyle/vivliostyle-pub/issues/82)

## その他報告

- フォントベンダーとの提携協議→ @ogwata
- 外部企業からの受託開発の報告→ @MurakamiShinyu
- CSS組版 Vivliostyle ユーザーと開発者の集い 2021秋の開催日程
- 技術書典以外の同人誌即売会への参加について

### Themes (@yamasy1549)

- [既存の公式テーマの名前を考え直す #56](https://github.com/vivliostyle/themes/issues/56)
    - →継続して議論。@akabekobeko は名前の一般性についてコメントする
- 「Vivliostyle で本を作ろう」を元にした新Themeは、機能を絞りシンプルなものとして再編する
    - → @spring-raining  の報告を待つ

### VFM

vivliostyle.org、docs.vivliostyle.orgにおけるVFMのドッグフィーディングの進め方について、@ogwata、@MurakamiShinyuは、[community](https://github.com/vivliostyle/community)にIssue登録する

### npm管理関連

- Node.jsの Requirement versionについて、下限をv12とする
  - Themes (@yamasy1549) →[Node.jsの Requirement version を設定する #59](https://github.com/vivliostyle/themes/issues/59)
  - create-book (@akabekobeko) Issue登録する

### vivliostyle.org (@yamasy1549)

- [ FAQページの更新 #83 ](https://github.com/vivliostyle/vivliostyle.org/issues/83)

### Vivliostyle Pub (@takanakahiko)

（後刻、別途 @takanakahiko、@ogwata、@MurakamiShinyuの3人で協議）

- 9/14に最低限度の機能を実装するバージョンを完成させる

### その他

- CSS組版 Vivliostyle ユーザーと開発者の集い 2021秋の開催日程
    - Slack [#meetup](https://vivliostyle.slack.com/archives/CUSJT7CFK)で議論する
- 技術書典以外の同人誌即売会への参加 →継続議論
- 逢賀サクさんたちとなにかコラボできないか検討 (@ogwata)

### 次回日程

- 10月2日（土曜）14時から

## Members

- @MurakamiShinyu
- @ogwata
- @AyumuTakai
- @akabekobeko (Scribe)

**Comment by ogwata** [comment]
議題を考えてみました。過不足があればご指摘ください。

----------------------------------------------

[前月](https://github.com/vivliostyle/community/issues/90)の振り返りと進捗報告（プロダクトごとに前回合意事項からの進捗を報告）


## Core and Viewer (@MurakamiShinyu)

- 前月合意事項
    - vivliostyle-view.js について
        - 告知のためブログを執筆→@MurakamiShinyu
- 前月からの進捗報告

## CLI (@spring-raining)

- 前月からの進捗報告

## Themes (@yamasy1549)

- 前月合意事項
    - 同人誌themeについて、逢賀サクさんの素材データを元に作成する
- [既存の公式テーマの名前を考え直す #56](https://github.com/vivliostyle/themes/issues/56)
    - →議論し忘れ、Issueで継続議論しましょう→everyone
- 「Vivliostyle で本を作ろう」を元にした新Themeは、機能を絞りシンプルなものとして再編する
    - → @spring-raining  の報告を待つ

## VFM (@akabekobeko)

- 前月合意事項
    - ["Vivliostyle Flavored Markdown: Working Draft"](https://vivliostyle.github.io/vfm/#/vfm#table-of-contents) のタイトルにある「Working Draft」はそのまま削除する
- 前月からの進捗報告

## npm管理関連

- 前月合意事項
    - Node.jsの Requirement versionについて、下限をv12とする
    - Vivliostyleプロダクト全体で下限を一致させる必要があるので、各担当者はプロジェクトごとにIssueを作成して、下限を設定する
        - Core and Viewer→@MurakamiShinyu
        - CLI →@spring-raining
        - Themes (@yamasy1549) →[Node.jsの Requirement version を設定する #59](https://github.com/vivliostyle/themes/issues/59)
        - Vivliostyle Pub →@takanakahiko
    - native ESMの対応は来年以降、状況を見極めつつおこなう

## vivliostyle.org (@yamasy1549)

- 前月合意事項
    - VFM 1.0.2リリースにともない、[今後の開発予定](https://vivliostyle.org/ja/documents/#%E4%BB%8A%E5%BE%8C%E3%81%AE%E9%96%8B%E7%99%BA%E4%BA%88%E5%AE%9A)のVFMの項は、[v2.0.0](https://github.com/vivliostyle/vfm/milestone/1)に変更する →[VFM注目のissueをv2.0.0のmilestoneに変更する #95](https://github.com/vivliostyle/vivliostyle.org/issues/95)
    - [FAQページの更新 #83](https://github.com/vivliostyle/vivliostyle.org/issues/83)

## Vivliostyle Pub (@takanakahiko)

- [ オープンベータまでのTo Doを考える（開発） #89 ](https://github.com/vivliostyle/vivliostyle-pub/issues/89)
- [ オープンベータまでのTo Doを考える（開発以外） #82 ](https://github.com/vivliostyle/vivliostyle-pub/issues/82)

## その他報告

- フォントベンダーとの提携協議→ @ogwata
- 外部企業からの受託開発の報告→ @MurakamiShinyu

**Comment by ogwata** [comment]
合意事項をまとめてみました。過不足や間違いがあれば言ってください。


## 合意事項

### Themes (@yamasy1549)

- [既存の公式テーマの名前を考え直す #56](https://github.com/vivliostyle/themes/issues/56)
    - →継続して議論。@akabekobek は名前の一般性についてコメントする
- 「Vivliostyle で本を作ろう」を元にした新Themeは、機能を絞りシンプルなものとして再編する
    - → @spring-raining  の報告を待つ

### VFM

vivliostyle.org、docs.vivliostyle.orgにおけるVFMのドッグフィーディングの進め方について、@ogwata、@MurakamiShinyuは、[community](https://github.com/vivliostyle/community)にIssue登録する

### npm管理関連

- Node.jsの Requirement versionについて、下限をv12とする
        - Themes (@yamasy1549) →[Node.jsの Requirement version を設定する #59](https://github.com/vivliostyle/themes/issues/59)
        - create-book (@akabekobek) Issue登録する

### vivliostyle.org (@yamasy1549)

- [ FAQページの更新 #83 ](https://github.com/vivliostyle/vivliostyle.org/issues/83)

### Vivliostyle Pub (@takanakahiko)

（後刻、別途 @takanakahiko、@ogwata、@MurakamiShinyuの3人で協議）

- 9/14に最低限度の機能を実装するバージョンを完成させる

### その他

- CSS組版 Vivliostyle ユーザーと開発者の集い 2021秋の開催日程
    - Slack [#meetup](https://vivliostyle.slack.com/archives/CUSJT7CFK)で議論する
- 技術書典以外の同人誌即売会への参加 →継続議論
- 逢賀サクさんたちとなにかコラボできないか検討 (@ogwata)


### 次回日程

- 10月2日（土曜）14時から
