### ISSUE TITLE
October 2021

### ISSUE THREAD

**Issue by akabekobeko** [vivliostyle/community#92]
|date | time | location|
|:--:|:--:|:--:|
|October 2, 2021 JST | 14:00-16:00 |Online|

- [Meeting Log](https://github.com/vivliostyle/community/blob/master/slack-logs/meeting-log/2021/2021-10-02.md)

## Core and Viewer (@MurakamiShinyu)

- 前月からの進捗報告
    - v2.11 での変更点
    - 10月に予定している機能追加
        - CSS text-spacing（約物詰め・和欧文間アキ）
        - CSS Grid Layout
        - CSS Custom Properties
- 検討事項
    - Coreの機能追加に関連して、Themesの次のissueについて議題にしたい
        - https://github.com/vivliostyle/themes/issues/67

## CLI (@spring-raining)

- 前月からの進捗報告
- [webpub2epub](https://github.com/AyumuTakai/webpub2epub) のデモ（@Ayumu Takai ）

## Themes (@yamasy1549)

- 前月合意事項 
    - [既存の公式テーマの名前を考え直す #56](https://github.com/vivliostyle/themes/issues/56)
        - →継続して議論。@akabekobeko は名前の一般性についてコメントする
    - 「Vivliostyle で本を作ろう」を元にした新Themeは、機能を絞りシンプルなものとして再編する
        - → @spring-raining  の報告を待つ

## VFM

- 前月合意事項 
    - vivliostyle.org、docs.vivliostyle.orgにおけるVFMのドッグフィーディングの進め方について、@ogwata、@MurakamiShinyuは、[community](https://github.com/vivliostyle/community)にIssue登録する
- 前月からの進捗報告

## npm管理関連

- 前月合意事項 
    - Node.jsの Requirement versionについて、下限をv12とする
        - Themes (@yamasy1549) →[Node.jsの Requirement version を設定する #59](https://github.com/vivliostyle/themes/issues/59)
        - create-book (@akabekobeko) Issue登録する
        - [Required Node.js LTS · Issue #34 · vivliostyle/create-book](https://github.com/vivliostyle/create-book/issues/34) 対応済み

## vivliostyle.org (@yamasy1549)

- 前月合意事項 
    - [ FAQページの更新 #83 ](https://github.com/vivliostyle/vivliostyle.org/issues/83)
- 前月からの進捗報告

## Vivliostyle Pub (@takanakahiko)

- 前月からの進捗報告
- 今後の開発方針について討議
    - [Vivliostyle Pub v1 Req](https://github.com/vivliostyle/community/wiki/Vivliostyle-Pub-v1-Req)の加筆

## その他

-  CSS組版 Vivliostyle ユーザーと開発者の集い 2021秋の開催日程 (@ogwata)について

### Core and Viewer

- 2.11リリースの速報的なブログを@ogwataが書く

### CLI

- Coreが無変更でViewerのみアップデートしリリースした場合、`--version`オプションを指定するとCoreの未来のバージョンを出力してしまう件（[ vivliostyle-cli #217](https://github.com/vivliostyle/vivliostyle-cli/issues/217)）
    - →CLIのコードの変更ではなく、Core の更新を待ってCLIをリリースする運用で解決を図る
- [feat: Improve PDF metadata (#97) #210 ](https://github.com/vivliostyle/vivliostyle-cli/pull/210)に関連して、press-ready を通すとChromiumのバージョンが上書きされて出力される件
    - →元の情報を連結するIssueを@MurakamiShinyu が作成する
- ページめくりの方向について、何を単位とするのか@MurakamiShinyu がIssueを作成する

### Themes

- 既存のThemeはいったんリセットすることも視野に入れ、どうすれば持続的に開発と運用ができるか検討する
    - →開発と運用のためのIssueを@akabekobekoが作成する
    - →テーマのガイドライン (開発編) の担当を@yamasy1549とする
    - →元の [既存の公式テーマの名前を考え直す #56 ](https://github.com/vivliostyle/themes/issues/56)は、@ogwataがクローズする

### Vivliostyle Pub

- Pull requestのレビュアーに@spring-rainingを加える

### CSS組版 Vivliostyle ユーザーと開発者の集い 2021秋

- 開催日は11月13日（土曜）とする
- テーマと登壇者の原案を@ogwataが作成し、Slackの meetupチャンネルに投稿する
- 当初はVivliostyle Pubのベータ版公開をメインにするつもりだったが、現段階で焦りは禁物なので、イベントに合わせて無理に開発を進めないようにする

## Members

- @MurakamiShinyu
- @ogwata
- @spring-raining
- @yamasy1549
- @AyumuTakai
- @yisoda
- スズキタイヨウ
- @akabekobeko (Scribe)

**Comment by ogwata** [comment]
今週末10/2に予定されている開発者会議の議題を考えてみました。
他に話し合いたいこと、外した方がよいこと等、ご意見ください。


----------------------------

## Core and Viewer (@MurakamiShinyu)

- 前月からの進捗報告
    - v2.10 での変更点
    - v2.11（近日中）Viewerに検索機能追加
    - 10月に予定している機能追加
        - CSS text-spacing（約物詰め・和欧文間アキ）
        - CSS Grid Layout
        - CSS Custom Properties
- 検討事項
    - Coreの機能追加に関連して、Themesの次のissueについて議題にしたい
        - https://github.com/vivliostyle/themes/issues/67

## CLI (@spring-raining)

- 前月からの進捗報告
- [webpub2epub](https://github.com/AyumuTakai/webpub2epub) のデモ（@Ayumu Takai ）

## Themes (@yamasy1549)

- 前月合意事項 
    - [既存の公式テーマの名前を考え直す #56](https://github.com/vivliostyle/themes/issues/56)
        - →継続して議論。@akabekobeko は名前の一般性についてコメントする
    - 「Vivliostyle で本を作ろう」を元にした新Themeは、機能を絞りシンプルなものとして再編する
        - → @spring-raining  の報告を待つ

## VFM

- 前月合意事項 
    - vivliostyle.org、docs.vivliostyle.orgにおけるVFMのドッグフィーディングの進め方について、@ogwata、@MurakamiShinyuは、[community](https://github.com/vivliostyle/community)にIssue登録する
- 前月からの進捗報告


## npm管理関連

- 前月合意事項 
    - Node.jsの Requirement versionについて、下限をv12とする
        - Themes (@yamasy1549) →[Node.jsの Requirement version を設定する #59](https://github.com/vivliostyle/themes/issues/59)
        - create-book (@akabekobeko) Issue登録する


## vivliostyle.org (@yamasy1549)

- 前月合意事項 
    - [ FAQページの更新 #83 ](https://github.com/vivliostyle/vivliostyle.org/issues/83)
- 前月からの進捗報告

## Vivliostyle Pub (@takanakahiko)

- 前月からの進捗報告
- 今後の開発方針について討議
    - [Vivliostyle Pub v1 Req](https://github.com/vivliostyle/community/wiki/Vivliostyle-Pub-v1-Req)の加筆


## その他

-  CSS組版 Vivliostyle ユーザーと開発者の集い 2021秋の開催日程 (@ogwata)について

**Comment by MurakamiShinyu** [comment]
"v2.11（近日中）Viewerに検索機能追加" の "（近日中）" はリリース済みなので削除しました。

**Comment by akabekobeko** [comment]
@MurakamiShinyu 
その項を削除して代わりに `v2.10 での変更点` を `v2.11 での変更点` へ修正しました。

**Comment by ogwata** [comment]
合意事項をまとめてみました。勘違いや抜けがあればご指摘ください


## 合意事項

### Core and Viewer

- 2.11リリースの速報的なブログを@ogwataが書く

### CLI

- Coreが無変更でViewerのみアップデートしリリースした場合、`--version`オプションを指定するとCoreの未来のバージョンを出力してしまう件（[ vivliostyle-cli #217](https://github.com/vivliostyle/vivliostyle-cli/issues/217)）
    - →CLIのコードの変更ではなく、Core の更新を待ってCLIをリリースする運用で解決を図る
- [feat: Improve PDF metadata (#97) #210 ](https://github.com/vivliostyle/vivliostyle-cli/pull/210)に関連して、press-ready を通すとChromiumのバージョンが上書きされて出力される件
    - →元の情報を連結するIssueを@MurakamiShinyu が作成する
- ページめくりの方向について、何を単位とするのか@MurakamiShinyu がIssueを作成する

### Themes

- 既存のThemeはいったんリセットすることも視野に入れ、どうすれば持続的に開発と運用ができるか検討する
    - →開発と運用のためのIssueを@akabekobekoが作成する
    - →テーマのガイドライン (開発編) の担当を@yamasy1549とする
    - →元の [既存の公式テーマの名前を考え直す #56 ](https://github.com/vivliostyle/themes/issues/56)は、@ogwataがクローズする


### Vivliostyle Pub

- Pull requestのレビュアーに@spring-rainingを加える


### CSS組版 Vivliostyle ユーザーと開発者の集い 2021秋

- 開催日は11月16日（土曜）とする
- テーマと登壇者の原案を@ogwataが作成し、Slackの meetupチャンネルに投稿する
- 当初はVivliostyle Pubのベータ版公開をメインにするつもりだったが、現段階で焦りは禁物なので、イベントに合わせて無理に開発を進めないようにする

**Comment by akabekobeko** [comment]
合意事項の掲載と議事録のリンクを終えたので close します。
