### ISSUE TITLE
vivliostyle.org、docs.vivliostyle.orgにおけるVFMのドッグフィーディングの進め方

### ISSUE THREAD

**Issue by ogwata** [vivliostyle/community#93]
現在、vivliostyle.org は Jekyll を使い、docs.vivliostyle.org は Docute を使いMarkdownを処理しています。したがって、どちらのMarkdownもVFMとは違いがあります。

サイトを立ち上げたばかりの頃は仕方ありませんが、今の私達には[Vivliostyle Flavored Markdown (VFM)](https://github.com/vivliostyle/vfm)があります。つい最近1.0をリリースしたこともあり、VFMの普及のためにも私達自身が積極的に使っていきたいところです。

vivliostyle.org、docs.vivliostyle.org におけるドッグフィーディングの進め方について討議したいと思います。皆さん、ぜひ知恵をお貸しください。

**Comment by ogwata** [comment]
現状、考えられる課題をメモしておきます。

- Vivliostyleのサイトは、複数のリポジトリにまたがっている
- Markdownの処理系も[vivliostyle.org](https://vivliostyle.org/) は [Jekyll](http://jekyllrb-ja.github.io/)、[Vivliostyle Docs](https://docs.vivliostyle.org/#/ja/)、[Vivliostyle Pub Docs](https://vivliostyle.github.io/docs-vivliostyle-pub/#/ja/)は [Docute](https://docute.org/guide/markdown-features) と異なっている
- 過去の資産との互換性をどう確保するか
   - 以前のコンテンツを修正加筆する際まで、全面的にVFMに書き換えが必要になるような事態は避けないといけない

**Comment by yamasy1549** [comment]
現在vivliostyle.orgは[GitHub Pagesでビルド](http://jekyllrb-ja.github.io/docs/github-pages/)しており、そのおかげでローカル環境でビルドすることなくページを更新できています（たとえば、GitHub上でブログ記事を編集してそのまま投稿するなど）。

Jekyllでは[カスタムMarkdownプロセス](http://jekyllrb-ja.github.io/docs/configuration/markdown/)により独自の記法をHTMLに変換することができます。この機能を使ってブログ記事などをVFMで書くことはできるはずですが、GitHub Pagesでビルドする際には使えないのでローカル環境でのビルドが必須になります。VFMをとるか、ローカル環境でのビルド不要をとるか、どちらかだと思います。

Vivliostyle.jsをCDNにして……という話が前にあったと思うのでそちらが使えるかもしれませんが、Jekyllとうまく併用できるかはちょっとわかりません。

**Comment by akabekobeko** [comment]
これを使えばいけるかもしれません。

- [peaceiris/actions-gh-pages: GitHub Actions for GitHub Pages 🚀 Deploy static files and publish your site easily. Static-Site-Generators-friendly.](https://github.com/peaceiris/actions-gh-pages)
- [GitHub Actions による GitHub Pages への自動デプロイ - Qiita](https://qiita.com/peaceiris/items/d401f2e5724fdcb0759d)

GitHub Actions の workflow として VFM のビルドと actions-gh-pages 呼び出しによるデプロイを定義することになります。ビルドについては Static Site Generator 系のツールを単純化したようなプロジェクトを作成して実験するのがよさそうです。

**Comment by akabekobeko** [comment]
SSG 部分を参考にするなら GatsbyJS ですかね。私のブログはこれで構築して Netlify でホストしています。GatsbyJS を参考に最低限の機能を実装するとしたらこんな感じでしょうか。

- `src/pages/` 配下の Markdown を VFM で `public/` に HTML をビルドする
- `src/pages/` 配下の Markdown からリンクされてるリポジトリー内ファイルを `public/` にコピーする
  - 相対リンク対象だけをコピーする
  - 参考 [akabekobeko/npm-gatsby-remark-copy-relative-linked-files](https://github.com/akabekobeko/npm-gatsby-remark-copy-relative-linked-files) 
- `src/static/` 配下の画像素材などを `public/` にコピーする
  - 静的 CSS を置けばそのままコピーされる
  - CSS は `src/scsss/` に SCSS を置いてそれを Transpile したものを `public/` に出力でもよい

もしくは GatsbyJS の [gatsby-transformer-remark](https://www.gatsbyjs.com/plugins/gatsby-transformer-remark/) だけを VFM に置き換えられれば GatsbyJS の知見とエコシステムをそのまま利用できてよいですね。

**Comment by ogwata** [comment]
@akabekobeko 

ありがとうございます。
よく分かってないのですが、GitHub Actions + GatsbyJS でVFMを使えそう、ということでよろしいでしょうか。
その場合、上記の「過去のコンテンツとの互換性確保が必要 」という部分はどういう実装になるのでしょう？

**Comment by yamasy1549** [comment]
ref: https://github.com/vivliostyle/vivliostyle.org/issues/101

**Comment by ogwata** [comment]
vivliostyle/vivliostyle.org#101 が作成され、そちらで本Issueが参照されているので、クローズしましょう。
