### ISSUE TITLE
Vivliostyle 開発者会議の URL 告知について検討する

### ISSUE THREAD

**Issue by akabekobeko** [vivliostyle/community#98]
現在の URL 告知はVivliostyle  Slack 上でおこなわれている。これをより広く訴求する場所にできないか検討する。

**Comment by ogwata** [comment]
Vivliostyleはオープンソース開発ですから、コミッターを増やすことは常に重要な課題です。そのためには、まず毎月の開発者会議に参加してもらうのが最もスムースです。

以前はGoogle MeetのURLを直接Twitterに流していました。しかし昨年外部から開発者会議への乱入（荒し）がありました。そこで再発防止のため、開発者会議の参加URLはあらかじめSlack #general 及びFacebook [Vivliostyleページ](https://www.facebook.com/vivliostyle)に掲載し、開催の数日前にTwitterでFacebookのURLを告知することに変更しました。

しかしFacebookは年齢層が高く、必ずしもVivliostyleがリーチしたい層と同じではありません。今よりも参加者を増やすためには、告知媒体に変更する必要があるでしょう。今のところ出されているのは以下の3案です。

- 月毎に作成されるGitHub communityリポジトリの開発者会議用Issue（[ogwata](https://github.com/ogwata)）
    - 利点：手間が少ない
    - 欠点：アカウント不要で見られるのでセキュリティに不安あり
- compassで毎回募集サイトを作成する（[akabekobeko](https://github.com/akabekobeko)）
    - 利点：手間がかかる
    - 欠点：アカウント不要で見られるのでセキュリティに不安あり
- Slack #general（[MurakamiShinyu](https://github.com/MurakamiShinyu)）
    - 利点：手間が少ない
    - 欠点：見るにはアカウントが必要でありセキュリティに不安なし

以上のように整理すると、Slackが最も良いように見えます。しかし、セキュリティを高めることで、かえって敷居を高くしてしまうことが懸念されます。

さらに言えば、アカウントが必要なプラットフォームで告知するのは、むしろ過剰防衛かもしれません。というのは、乱入者の侵入経路はTwitterに限定されると推測されるからです（当時、Twitter状で`https://meet.google.com/`で検索したら、無数のmeet告知がヒット。現在はフィルタリングされている）。昨年の乱入者は英語話者だったことを思い出してください。つまり、TwitterのようなプラットフォームでURLを流さないようにすれば、あのような乱入者は防げるはずです。

そうすると、残りはGitHubとcompassですが、本来の目的である開発者勧誘を重視すると、compassの方を指示したいと思います。イベントの作成と同時に登録者へメールで告知が届くなど、GitHubよりも募集という機能が高いからです。作成の手間を私が負担することになりますが、最も負荷のかかる文章作成は現在の告知方法とあまり変わらないので、それほど負担は変わらないと見込んでいます。

なお、この議論整理は #97 合意事項「開発者会議の告知方法を変更する件」にもとづくものです。より詳しい経緯はこちらを参照してください。

**Comment by akabekobeko** [comment]
@ogwata 

私が connpass を提案した際、参加者だけに通知を出す機能を使えばアカウント不要の閲覧を防げるという話をしました。よって以下の欠点は少なくともアクセス制御をしていることにより Slack 並なので、他の候補との比較要素にはならないのではないでしょうか？

> - compassで毎回募集サイトを作成する（[akabekobeko](https://github.com/akabekobeko)）
>     - 利点：手間がかかる
>     - 欠点：アカウント不要で見られるのでセキュリティに不安あり

- [参加者へ一括メッセージを送る — connpassご利用ガイド ドキュメント](https://help.connpass.com/organizers/bulk-message.html)

それと `利点：手間がかかる` は欠点側だと思います。まとめると

- 利点
  - 参加者だけのメッセージ送信を利用することで URL の公開範囲を限定できる
  - 開発者会議の存在自体はイベントとしてアクセス制限なしに公開可能
  - ユーザーがグループ登録すれば継続的にイベント通知を自動配信できる
- 欠点
  - 手間がかかる

のようになります。

**Comment by akabekobeko** [comment]
もうひとつ connpass のイベント画面に「参加者への情報」という欄があり、これはメール通知なしで管理者、発表者、参加者に限定公開する情報を登録できます。

- [イベントを作成する — connpassご利用ガイド ドキュメント](https://help.connpass.com/organizers/event-detail.html)

過去に私が参加したイベントではここに Zoom や Meet の URL を公開するものもありました。

**Comment by UskeS** [comment]
@akabekobeko さんの仰るとおり，僕が主催するもくもく会でそのように使っています。
[前回のイベント](https://dtpmkmk.connpass.com/event/236726/)を見ていただけるとわかると思います。

参加者には下図のように表示される仕組みです。
<img width="731" alt="スクリーンショット_2022-03-24_13_36_36" src="https://user-images.githubusercontent.com/32891783/159843591-cc236678-2a43-47fb-a6fa-178cfc05ad38.png">

**Comment by ogwata** [comment]
今のところ、3人がcompass案支持ですが、他の案を支持という方はいないでしょうか。
[MurakamiShinyu](https://github.com/MurakamiShinyu)さんはいかがですか？

**Comment by MurakamiShinyu** [comment]
@ogwata connpass利用で問題ありません。

**Comment by akabekobeko** [comment]
今回の May 2022 を connpass で告知されたので本件は close します。
